### ISSUE TITLE
`valuePublisher` does not publish when an `Object`'s `LinkingObjects` is updated.

### ISSUE THREAD

**Issue by Zanchee** [realm/realm-swift#7591] opened 2021-12-26 15:14 UTC
### How frequently does the bug occur?

All the time

### Description

I have two objects...

```
class Recipe: Object {
    @Persisted(originProperty: "recipe") var brews: LinkingObjects<Brew>
}
```

and 

```
class Brew: Object {
    @Persisted var recipe: Recipe?
}
```

I have a `valuePublisher(myRecipe)` but it does not publish changes when I create a new `Brew` that references `myRecipe`

### Can you reproduce the bug?

Yes, always

### Version

10.20.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14

### Build environment

Xcode version: 13.2.1
Dependency manager and version: SPM

**Comment by leemaguire** [comment] 2021-12-29 16:55
Hi @Zanchee I cannot reproduce your issue. Could you attach a more detailed test case that reproduces this?

**Comment by Zanchee** [comment] 2022-01-05 20:52
Here is a fully functioning example. I also attached the project.

```swift
import UIKit
import Combine
import RealmSwift

class Foo: Object {
    @Persisted(primaryKey: true) var id: UUID
    @Persisted(originProperty: "foo") var bars: LinkingObjects<Bar>
}

class Bar: Object {
    @Persisted(primaryKey: true) var id: UUID
    @Persisted var foo: Foo?
}


@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    var cancellable: AnyCancellable?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let realm = try! Realm()

        let foo = Foo()
        try! realm.write {
            realm.add(foo)
        }

        cancellable = valuePublisher(foo).sink { completion in
            print("End of publisher.")
        } receiveValue: { foo in
            print("Foo Changed: \(foo.bars.count)") // Expected 3 hits... (Never hit!)
        }

        try! realm.write {
            let barOne = Bar()
            barOne.foo = foo
            realm.add(barOne)

            let barTwo = Bar()
            barTwo.foo = foo
            realm.add(barTwo)

            let barThree = Bar()
            barThree.foo = foo
            realm.add(barThree)
        }

        print("End Write:", foo.bars.count) // Expected Output - "End Write: 3"

        return true
    }

    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }
}

[Example.zip](https://github.com/realm/realm-swift/files/7817720/Example.zip)

```

**Comment by Zanchee** [comment] 2022-01-05 21:03
Could this potentially be related to #7493?

**Comment by pavel-ship-it** [comment] 2022-01-06 09:51
Hi @Zanchee 
Unfortunately it looks like it's 7493.
As a workaround you can observe the foo.bars directly
```
        cancellable = foo.bars.changesetPublisher.sink { _ in
        } receiveValue: { changes in
            print("Foo Changed: \(changes)")
        }
```

**Comment by Zanchee** [comment] 2022-01-06 12:54
@pavel-ship-it it seems like the author of the other issue may know what the actual issue is, is this something that belongs on the realm core repo vs the realm swift one? I'm using that workaround for now, but definitely would like to avoid it in the future if possible.

**Comment by pavel-ship-it** [comment] 2022-01-06 17:38
@Zanchee yes, we have a ticket concerning this issue in core repository too. 

If you don't mind I'll close this issue as a duplicate of #7493. You can track the status by subscribing on the related issue updates.

**Closed by pavel-ship-it** 2022-01-06 17:38 UTC
Labels: T-Bug, O-Community, Needs-Attention
