### ISSUE TITLE
Error Domain=io.realm Code=2 "Unable to open a realm at path" Operation not permitted

### ISSUE THREAD

**Issue by mungbeans** [realm/realm-swift#7596] opened 2022-01-03 16:28 UTC
### Problem

https://github.com/realm/realm-swift/issues/6096 says "For anyone still encountering the initial issue, please upgrade to the latest version of Realm."

With an iOS application in Testflight using 10.20.1 a crash in Tesflight was observed with:

 Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/private/var/mobile/Containers/Shared/AppGroup/0E81CAED-B1AF-4684-87FB-0D1EDE2F1392/collections.lock': open() failed: Operation not permitted Path: /private/var/mobile/Containers/Shared/AppGroup/0E81CAED-B1AF-4684-87FB-0D1EDE2F1392/collections.lock Exception backtrace: 0 NotificationServiceExtension 0x0000000100aa3ac8 _ZNK5realm5Table10find_firstINS_4util8OptionalINS_8ObjectIdEEEEENS_6ObjKeyENS_6ColKeyET_ + 105748 1 NotificationServiceExtension 0x0000000100973194 _ZNK5realm19ArrayFixedBytesNullINS_4UUIDELi16EE15find_first_nullEmm + 127436 2 NotificationServiceExtension 0x0000000100976464 _ZNK5realm19ArrayFixedBytesNullINS_4UUIDELi16EE15find_first_nullEmm + 140444 3 NotificationServiceExtension 0x000000010097a9c0 _ZNK5realm19ArrayFixedBytesNullINS_4UUIDELi16EE15find_first_nullEmm + 158200 4 NotificationServ

Crashed: com.apple.NSXPCConnection.user.endpoint
EXC_BREAKPOINT 0x0000000184e7d5a8
Crashed: com.apple.NSXPCConnection.user.endpoint
0  libswiftCore.dylib              0x3a5a8 _assertionFailure(_:_:file:line:flags:) + 304
1  libswiftCore.dylib              0xa0f34 swift_unexpectedError + 560

The Realm database was attempting to be accessed from within a Notification Service Extension, it is not encrypted.

It is so far unreproducible on demand, however only a handful of people are using the app in Testflight, so even one occurrance observed out of a handful of users is extreemly worrying when extrapolated to millions of users.

### How important is this improvement for you?

Dealbreaker

**Comment by leemaguire** [comment] 2022-01-04 13:55
Hi @mungbeans,

Can you show us how you are opening the Realm in your extension? Have you added `NSFileProtectionNone` to the Realm location? I'm thinking this might be caused by file access while the device is locked.

**Comment by mungbeans** [comment] 2022-01-04 15:10
Hi @leemaguire 

Ah, no I haven't NSFileProtectionNone, I was under the assumption that was the default value if you didn't do anything explicitly.

Here's how its being opened
 let db = RealmDatabase.instance()
 db.openOrCreateDatabase() 


@objc class RealmDatabase : NSObject {
    var configuration:Realm.Configuration?  		= nil

    @objc public class func instance() -> RealmDatabase {
        return realmDatabaseInstance
    }
    private static var realmDatabaseInstance: RealmDatabase = {
        let realmSingleton = RealmDatabase()
        return realmSingleton
    }()

    @objc func openOrCreateDatabase() {
        var url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: ExtensionSettingsManager.sharedGroupContainerName())!
        url = url.appendingPathComponent("collections")
        self.configuration = Realm.Configuration(fileURL: url)
    }

**Comment by leemaguire** [comment] 2022-01-04 15:45
Could you try:
```swift
    @objc func openOrCreateDatabase() {
        var url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "")!
        // Disable file protection for this directory
        try! FileManager.default.setAttributes([.protectionKey: FileProtectionType.none],
                                               ofItemAtPath: url.path)
        url = url.appendingPathComponent("collections")
        self.configuration = Realm.Configuration(fileURL: url)
    }
```

**Comment by mungbeans** [comment] 2022-01-04 16:16
Yes I'll add that and then keep an eye out on it to see if it happens again. Thanks

**Comment by dianaafanador3** [comment] 2022-01-26 18:49
@mungbeans closing this, if you still have issues with this after applying the below suggestion feel free to open again this issue.

**Closed by dianaafanador3** 2022-01-26 18:49 UTC
Labels: T-Enhancement, O-Community, Waiting-For-Reporter
