### ISSUE TITLE
Client Reset problems since Version 10.41

### ISSUE THREAD

**Issue by divan84** [realm/realm-swift#8296] opened 2023-07-11 09:11 UTC
### How frequently does the bug occur?

Always

### Description

I'm currently working on a project using Device Sync and managing Flexible Sync Rules/Permissions for realm objects via custom user data. (similar to: [https://www.mongodb.com/docs/atlas/app-services/sync/app-builder/device-sync-permissions-guide/#restricted-news-feed]())

We achieved to get "automatic permission" updates in the client, through observing the Custom User Data Collection - if something changes here we suspend the syncsession of the the current open realm. Then we are refreshing the users custom user data, resuming the realms synssession and then reopen the realm.

The codesnippet for this is: 

   ```
self.userRealm?.syncSession?.suspend()
                 _ = try await user.refreshCustomData()
                 self.userRealm?.syncSession?.resume()
                 openRealm()

 func openRealm() {
             self.userRealm = try Realm(configuration: configuration, queue: .main)        }
     }

```
the sync config is :
```
var configuration = user.flexibleSyncConfiguration(clientResetMode: .recoverUnsyncedChanges(), initialSubscriptions: { subscriptions in
            self.addSubscriptions(subscriptions)
        }, rerunOnOpen: true)

```
This forces a client reset and updates the realm data with the new Sync Rules and subsequently updates our SwiftUI Views with the new data...

It sounds hacky - but It seemed to be the only way to get the correct data after the custom user data changed and therefore the sync rules for the objects...

Since the latest Realm Version 10.41 this workaroung doens't work anymore - there is no client reset triggered by the code above..

How to make the Client Reset work again?

### Can you reproduce the bug?

Always

### Version

10.41

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS, macOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by dianaafanador3** [comment] 2023-07-11 09:13
@michael-wb any changes on recent version which can cause this to change

**Comment by michael-wb** [comment] 2023-07-11 13:34
There were updates related to client reset on async open in [PR 6723](https://github.com/realm/realm-core/pull/6723), but it is more related to changes to the schema, esp. additive changes. Maybe this is a side effect of this change? cc: @ironage

In general, Core prefers leaving it up to the server to determine when a client reset needs to be performed.

@divan84 - would it be possible to get debug logs to see what sync is doing?

**Comment by michael-wb** [comment] 2023-07-11 16:16
@divan84 Actually, this may be affected by the Session Multiplexing feature, where Realm will attempt to reuse existing connections for new sessions. With this feature, connections will remain open for a configurable "linger" time after the last session is closed before closing the connection with the server. I am thinking an existing connection is being reused when the session is reopened, which likely has cached custom user data (in the server) from when the connection was originally opened and does not have the most recent updates.

As a possible workaround, you can set the `SyncTimeoutOptions.connectionLingerTime` value to 0 (default is 30000 or 30s), which will close the connection immediately when the last session is closed, or set `AppConfiguration.enableSessionMultiplexing` to `false` to disable Session Multiplexing altogether.

**Comment by michael-wb** [comment] 2023-07-11 18:02
Oh right - thanks @ironage
Those were in last week's build and 10.41 is based on Core 13.15.1 (released June 16).

**Comment by divan84** [comment] 2023-07-12 05:11
The code above works on Realm Swift version 10.40.2. How long before that, I can't say. The problems only appear since version 10.41, on both macOS and iOS.

Unfortunately the suggested workaround doesn't work: Neither deactivating the session multiplexing nor setting the SyncTimeoutOptions helps...

I am attaching three log files - all three from the same situation on, where the notification is received that the custom user data has changed (as described above) - and should trigger the behavior described above...

The frist one using Realm Swift 10.40.2
The second one using Realm Swift 10.41, session multiplexing = true
The third one using Realm Swift 10.41,  session multiplexing = false

Hope this helps you!
[Three.txt](https://github.com/realm/realm-swift/files/12023935/Three.txt)
[One.txt](https://github.com/realm/realm-swift/files/12023936/One.txt)
[Two.txt](https://github.com/realm/realm-swift/files/12023937/Two.txt)

**Comment by divan84** [comment] 2023-07-17 06:02
Any news on the issue?
Can the log files help you in any way?

**Comment by dianaafanador3** [comment] 2023-07-18 07:24
There are some fixes associated to async-open/client reset in our latest version. @divan84 can you please check if you are still experiencing your issue?

**Comment by divan84** [comment] 2023-07-18 07:47
Unfortunately it doesn't solve the issue - still the same!

**Comment by dianaafanador3** [comment] 2023-07-18 07:48
@michael-wb can you please check the logs attached above

**Comment by divan84** [comment] 2023-08-04 13:37
@dianaafanador3 : Any updates on this problem?

**Comment by dianaafanador3** [comment] 2023-08-04 16:49
@michael-wb are there any updates on this issue? Do we have any idea why this behavior changed since 10.41.0 -> Core (13.15.1)? 
Seems like doing the below was triggering a client reset, which is not happening anymore? 
Maybe this was not the correct behaviour and was fixed, or there is a change in the server?
```
self.userRealm?.syncSession?.suspend()
_ = try await user.refreshCustomData()
self.userRealm?.syncSession?.resume()
```

**Comment by michael-wb** [comment] 2023-08-05 19:46
@divan84 - sorry for the delay. The logs were really helpful. The issue is the fact that `suspend()` is not disconnecting the connection, so the server is not refreshing the custom user data for the sessions when the connection is established:
```
Debug: Connection[1]: Session[3]: Initiating deactivation
Debug: Connection[1]: Session[3]: Sending: UNBIND
Debug: Connection[1]: Session[3]: Received: UNBOUND
Debug: Connection[1]: Session[3]: Deactivation completed
Debug: Connection[1]: Session[4]: Activating
Debug: Connection[1]: Session[4]: client_file_ident = 297, client_file_ident_salt = 3191762549198096150
Debug: Connection[1]: Session[4]: last_version_available  = 136
Debug: Connection[1]: Session[4]: progress_server_version = 1676
Debug: Connection[1]: Session[4]: progress_client_version = 133
Debug: Connection[1]: Session[4]: Sending: BIND(session_ident=4, need_client_file_ident=false, is_subserver=false, json_data="")
Debug: Connection[1]: Session[4]: Progress handler called, downloaded = 1326, downloadable(total) = 1326, uploaded = 1255, uploadable = 1255, reliable_download_progress = false, snapshot version = 136
```
After looking at the core code, it appears that even if session multiplexing is disabled or the linger time is 0, the connection is still waiting a non-zero amount of time for the session to close before the connection is terminated. Since you are resuming immediately (less than 470ms) the session is still being resumed within the window before the connection is closed.

A possible workaround, for now, would be to either close and open a new SyncSession instead of pausing and resuming or sleep/wait for a second or two (with multiplexing disabled or the linger time set to 0) to let the connection expire before trying to reconnect.

You can verify a new connection is being used by looking at the connection number to see if it has increased.

I will work with the Swift SDK team to see the best approach to provide a way to either force the connection to be closed and/or ensure the connection is closed when the last session is closed with session multiplexing disabled or the linger time is 0.

**Comment by michael-wb** [comment] 2023-08-08 18:20
@divan84 - would you be able to provide a complete log file with sync multiplexing disabled? I am specifically looking for this debug statement that displays the multiplexing value:
```
Config param: one_connection_per_session = true
```
it is possible that there is a disconnect between setting the value in Swift and it being applied to the Realm Core settings. If session multiplexing is disabled, there should only be exactly 1 session per connection and starting a new session will create a new connection (with the updated custom user data).

**Comment by divan84** [comment] 2023-08-09 11:58
@michael-wb : It looks like this parameter stays true.
Although I set the realmApp.configuration.enableSessionMultiplexing to false right at the start of the app...
More on this in the attached log file... 
[log.txt](https://github.com/realm/realm-swift/files/12302274/log.txt)

**Comment by divan84** [comment] 2023-08-09 12:04
@dianaafanador3 : 
Referring to the previous post:
I initialize the realm app as a global variable outside of each object and then set the SessionMultiplexing configuration in the init() of a singleton that manages my app, so at app startI  is set realmApp.configuration.enableSessionMultiplexing to false...

A little like the following snippet:

`private let REALM_APP = App(id: Bundle.appId)

public final class AppManager: ObservableObject {
    public static let shared = AppManager()
...
    private init() {
        REALM_APP.syncManager.logLevel = .debug
        REALM_APP.configuration.enableSessionMultiplexing = false
        ....
    }
`

Should setting the enableSessionMultiplexing Configuration be done differently?

**Comment by michael-wb** [comment] 2023-08-09 12:41
@divan84 - Thank you for the initialization code snippet. The `enableSessionMultiplexing` value is cached inside Core once the "App" is created, so you will need to provide the configuration when you create `App`. This is the same for the SyncTimeout values as well.
I believe the initialization would look something like this - @dianaafanador3, please correct me if I'm wrong:
```swift
private let appConfig = AppConfiguration(enableSessionMultiplexing: false)
// or 
// let appConfig = AppConfiguration(syncTimeouts: .init(connectionLingerTime: 1))
private let app = App(id: Bundle.appId, configuration: appConfig)
```

**Comment by divan84** [comment] 2023-08-09 12:57
@michael-wb 
It works like you said!
Thanks alot!

But one more question about the whole thing: As mentioned at the beginning in the initial post: it's a pretty hacky approach to get the  latest data synced to the client due to the latest flexible sync permissions and roles if something changes the permissions du to changes in the custom user data on the serverside...
Are there any other approaches for this use case? Or are you coming up with a server-side approach soon?

Best regards and again: Thank you very much!!

**Comment by nirinchev** [comment] 2024-02-05 11:46
Agree that it's hacky - I've relayed the feedback to the server team and they'll look into it. There's a different project in flight that may completely remove the need for a client reset when permissions change, so not sure if they'll choose to just wait for that one to complete instead.

**Closed by nirinchev** 2024-02-05 11:46 UTC
Labels: O-Community, Needs-Attention, Frequency:Always, Repro:Always, Encryption:Off, SDK-Use:Sync

**Comment by nirinchev** [comment] 2024-02-05 12:59
Just heard from the server team and they've actually fixed this and it was released 2 weeks ago. Now when your custom user data changes, the server will detect this and disconnect the user automatically.
