### ISSUE TITLE
`RLMSyncSession::errorHandler` issue

### ISSUE THREAD

**Issue by versoworks** [realm/realm-swift#7211] opened 2021-04-15 02:50 UTC
## Expected Results
When all sessions are revoked via the Realm admin console, the client receives a notification via the `RLMSyncSession::errorHandler`

## Actual Results
In our testing, no error is received via the `RLMSyncSession::errorHandler`

## Steps for others to Reproduce
Log a user in to a sync session.
Close the client without directly logging out the user.
Go to the Realm admin console > App Users and select _Revoke all sessions_ from the menu pertaining to the user.
Open the client and check whether `RLMSyncSession::errorHandler` raises an error when a sync session with the `RLMApp::currentUser` is initialised.

## Version of Realm and Tooling
Realm framework version: 10.7.2
Xcode version:12
iOS/OSX version: 14.4.2

**Comment by pavel-ship-it** [comment] 2021-04-19 10:10
Hi @versoworks , I'll look into this issue.

**Comment by pavel-ship-it** [comment] 2021-04-21 09:52
Hi @versoworks , thank you for submitting the issue here. I can reproduce it and I'll open a ticket to fix.

**Comment by versoworks** [comment] 2021-04-21 09:54
@pavel-ship-it  thank you for investigating so quickly, much appreciated.

**Comment by pavel-ship-it** [comment] 2022-01-27 15:07
Cannot reproduce
Fixed in [Handle error 401 Unauthorized realm/realm-core#4745](https://github.com/realm/realm-core/issues/4745)

**Closed by pavel-ship-it** 2022-01-27 15:07 UTC
Labels: O-Community
