### ISSUE TITLE
dyld: lazy symbol binding failed: can't resolve symbol _$s7Combine9PublishedVMa in 

### ISSUE THREAD

**Issue by chatarveer** [realm/realm-swift#7748] opened 2022-04-13 07:35 UTC
### How frequently does the bug occur?

All the time

### Description

RealmSwift  
 
spec.dependency "RealmSwift", "~> 10.25.1"

Xcode: Version 13.2.1 (13C100)
Simulator: iOS 12.4

Crashing constantly as app opens & tries to load combine which is not weak framework.

### Stacktrace & log output

```shell
dyld: lazy symbol binding failed: can't resolve symbol _$s7Combine9PublishedVMa in /Users/cveer/Library/Developer/CoreSimulator/Devices/6DA27B78-1B63-4ADE-97BA-935E2A094899/data/Containers/Bundle/Application/263CA9B6-BEAB-4146-BEA5-30096CFC76D5/SandboxApp.app/Frameworks/RealmSwift.framework/RealmSwift because dependent dylib #7 could not be loaded
dyld: can't resolve symbol _$s7Combine9PublishedVMa in /Users/cveer/Library/Developer/CoreSimulator/Devices/6DA27B78-1B63-4ADE-97BA-935E2A094899/data/Containers/Bundle/Application/263CA9B6-BEAB-4146-BEA5-30096CFC76D5/SandboxApp.app/Frameworks/RealmSwift.framework/RealmSwift because dependent dylib #7 could not be loaded
CoreSimulator 783.5 - Device: iPhone 7 (6DA27B78-1B63-4ADE-97BA-935E2A094899) - Runtime: iOS 12.4 (16G73) - DeviceType: iPhone 7
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Added in description.

### Version

10.25.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 12.4 and Realm 10.25.1

### Build environment

Xcode version: Version 13.2.1 (13C100)
Dependency manager and version: Cocoapods 1.11.3

**Comment by pavel-ship-it** [comment] 2022-04-13 11:45
Hi @chatarveer,
I cannot reproduce it by just installing via Cocoapods.
Can you show me your Podfile? Maybe a sample project?

**Comment by chatarveer** [comment] 2022-04-13 16:44
> Hi @chatarveer, I cannot reproduce it by just installing via Cocoapods. Can you show me your Podfile? Maybe a sample project?

I created SandboxApp & it seems working all alone, while when its with other libraries, it doesn't work. 
I will share Podfile with you asap, 

meanwhile if you can guide me whey we have no Combine as weak framework similar to SwiftUI in podspec of realm swift.

**Comment by chatarveer** [comment] 2022-04-13 16:46
Additionally, which is different in my project & Sandbox is dependency.

My project is

MainApp
 --Persistence  - Internal repo
    -Podspec of Persistence has 
         spec.dependency "RealmSwift", "~> 10.25.1"


I will make similar demo where it is added as Dependency of internal dependency. Can you try same way?

**Comment by leemaguire** [comment] 2022-04-19 10:04
I don't have an iOS 12.4 device to test this on but I cannot reproduce with the following podfile:

```
platform :ios, '12.4'

target 'TestPod' do
  use_frameworks!
  #FooBar is a dependancy of this target
end

target 'FooBar' do
  use_frameworks!
  pod "RealmSwift", "~> 10.25.1"
end
```

Could you also try weak link the Combine framework like so and see if that helps?
<img width="1338" alt="Screenshot 2022-04-19 at 11 04 28" src="https://user-images.githubusercontent.com/17234962/163980509-5e5746f6-b51e-4c0e-9100-03b47c70e63e.png">

**Comment by dianaafanador3** [comment] 2022-05-04 11:13
HI @chatarveer was the comment above helpful for you?
I tested this creating a pod which has RealmSwift as a subdependency and run it on a simulator with 12.4 (Xcode 13.2.1) and everything seems to be working fine. This the playground project I used if you want to take a look (https://github.com/dianaafanador3/Persistance/tree/master).
If you are still getting the error, please can you create a sample project reproducing the issue, so we can help you, if not please close this issue.

**Closed** 2022-05-31 09:29 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by aserdobintsev** [comment] 2022-09-14 07:41
Faced the same issue.

**How frequently does the bug occur?**

All the time on iOS 12.4. 
Works fine on iOS 13, 14, 15.

**Description**

Started to crash when have raised up the deployment target from iOS 11 up to iOS 12.4
Crashing constantly trying to init in memory Realm instance.

**Stacktrace & log output**

dyld: lazy symbol binding failed: can't resolve symbol _$s7Combine9PublishedVMa in /Users/aserdobintsev/Library/Developer/CoreSimulator/Devices/2A438260-053F-449B-90F2-22C3C2BF8130/data/Containers/Bundle/Application/D7F5DCFC-2BF7-489D-9103-6946740E1CC3/Modulbank.app/Frameworks/RealmSwift.framework/RealmSwift because dependent dylib #7 could not be loaded
dyld: can't resolve symbol _$s7Combine9PublishedVMa in /Users/aserdobintsev/Library/Developer/CoreSimulator/Devices/2A438260-053F-449B-90F2-22C3C2BF8130/data/Containers/Bundle/Application/D7F5DCFC-2BF7-489D-9103-6946740E1CC3/Modulbank.app/Frameworks/RealmSwift.framework/RealmSwift because dependent dylib #7 could not be 
CoreSimulator 802.6.1 - Device: iPhone 7 (2A438260-053F-449B-90F2-22C3C2BF8130) - Runtime: iOS 12.4 (16G73) - DeviceType: iPhone 7

Crash report:  [RealmCrashExample-2022-09-14-123800.ips.zip](https://github.com/realm/realm-swift/files/9563877/RealmCrashExample-2022-09-14-123800.ips.zip)


**Can you reproduce the bug?**

Yes, always.

 **Reproduction Steps**

Sample project with the only RealmSwift pod. [RealmCrashExample.zip](https://github.com/realm/realm-swift/files/9563730/RealmCrashExample.zip). 
Don't forget to install pods (removed Pods directory because of 500+ MB size).
Tap 'Init Realm' button.

**Version**

Sample project with RealmSwift version of 10.29.0.
In original work project crash occured on RealmSwift 10.12.0

**What SDK flavour are you using?**

InMemory database only

**Are you using encryption?**

No, not using encryption

**Platform OS and version(s)**

Simulator: iPhone 7 iOS 12.4 (16G73)

**Build environment**
macOS 12.5.1
Xcode Version 13.4.1 (13F100)
Cocoapods 1.11.3

**Comment by aserdobintsev** [comment] 2022-09-14 07:42
Will you reopen the issue or should I create a new one?

**Comment by dianaafanador3** [comment] 2022-09-14 17:03
@aserdobintsev this seems related to this https://github.com/realm/realm-swift/issues/7462, no need to open a new issue.

**Comment by aserdobintsev** [comment] 2022-09-15 01:13
@dianaafanador3 Thanks to pointing out the right issue. Will try to downgrade RealmSwift to 10.11.0.
