### ISSUE TITLE
Embedded object with to-one relationship

### ISSUE THREAD

**Issue by igorsquadra-anoki** [realm/realm-swift#8415] opened 2023-11-08 15:53 UTC
### How frequently does the bug occur?
Always

### Description
I'm having some issue with db structure.
I wasn't able to understand what is the best way to organize objects.

I have:

* 2 Object type: User and Book
* 1 EmbeddedObject type: Purchase
User has an array of purchases
Each Purchase has a reference to Book.
Book has no reference to Purchase (I don't need it).

```swift
class User: Object {
  @Persisted(primaryKey: true) var id: Int
  @Persisted var purchases: List<Purchase>
}

class Purchase: EmbeddedObject {
  @Persisted(indexed: true) var id: Int
  @Persisted var book: Book?
}

class Book: Object {
  @Persisted(primaryKey: true) var id: Int
}
```

I can successfully add and update books at various times without encountering any issues. 
However, when attempting to add a list of Purchase objects to a User, and some of these objects already contain existing books, it results in a crash with the following error message: 'Attempting to create an object of type 'Book' with an existing primary key value '1090'.' 
It appears that the system is attempting to create the same existing book once more, rather than establishing a relationship between the Purchase and the Book.

### Can you reproduce the bug?
Always

### Version
10.42.0

### What Atlas Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
iOS 17

### Build environment
```
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344

/Applications/Xcode.app/Contents/Developer
Xcode 15.0
Build version 15A240d

/opt/homebrew/bin/pod
1.13.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

carthage not found
(not in use here)

/usr/bin/git
git version 2.39.3 (Apple Git-145)
```

**Comment by Jaycyn** [comment] 2023-11-08 20:03
There are a couple of issues:

The first is that a Purchase (an embedded object) is not an independently managed object - it cannot exist on it's own. It only exists as part of another object. So adding existing purchase objects to a user would not be possible - other than if you're instantiating and populating those objects in memory.

The second issue is that primary keys in objects MUST be unique - e.g. you can't have two objects with the same primary key.

In this situation a book object with primary key 1090 is already persisted and you're trying to persist another object with the same primary key. If you want to update an existing object, you can follow the design pattern here [Update An Object](https://www.mongodb.com/docs/realm/sdk/swift/crud/update/#update-an-object) or you can do that with an [upsert](https://www.mongodb.com/docs/realm/sdk/swift/crud/update/#upsert-an-object)

IMO best practice is to not use integers as primary keys - they are inherently more difficult to work with and require more code. I suggest using ObjectID as shown [here](https://www.mongodb.com/docs/realm/sdk/swift/model-data/supported-types/#unique-identifierse).

**Comment by igorsquadra-anoki** [comment] 2023-11-09 08:26
Thank you for your response, @Jaycyn.
I have a couple of points that I'd like to clarify:

> The first is that a Purchase (an embedded object) is not an independently managed object - it cannot exist on it's own. It only exists as part of another object. 
> 
This aligns with my expectations for the model structure.

> So adding existing purchase objects to a user would not be possible - other than if you're instantiating and populating those objects in memory.
> 
Does this mean that I can only instantiate a User with its purchases and can't modify them later?

> The second issue is that primary keys in objects MUST be unique - e.g. you can't have two objects with the same primary key.
In this situation a book object with primary key 1090 is already persisted and you're trying to persist another object with the same primary key. If you want to update an existing object, you can follow the design pattern here [Update An Object](https://www.mongodb.com/docs/realm/sdk/swift/crud/update/#update-an-object) or you can do that with an [upsert](https://www.mongodb.com/docs/realm/sdk/swift/crud/update/#upsert-an-object)
> 
I understand that primary keys must be unique, and that makes sense. In my case, a book object with primary key 1090 is already persisted. However, when I try to add a new purchase to a user, it seems to be attempting to create a new object with the same primary key instead of modify the existing one. This is the primary problem I'm facing.

> IMO best practice is to not use integers as primary keys - they are inherently more difficult to work with and require more code. I suggest using ObjectID as shown [here](https://www.mongodb.com/docs/realm/sdk/swift/model-data/supported-types/#unique-identifierse).
>
Thanks for your suggestion!

My primary concern is finding the best way to establish relations between these objects. I'd love to hear your insights on this. 
Thank you!

**Comment by Jaycyn** [comment] 2023-11-09 18:10
> Does this mean that I can only instantiate a User with its purchases and can't modify them later?

You can always modify an object. However, you could not instantiate a Purchase object and persist it independently of a parent object. e.g. you can't create 10 Purchase objects, store them and then add them to another object 'later'. On the other hand, you could instantiate them in *memory only* (not persist them to disk) and add them to another object. An embedded object can't be added to multiple parent objects though - they are specific to only one parent object and become part of that parent object. If you add an embedded object to multiple parents, each is a copy and is independent data.

> In my case, a book object with primary key 1090 is already persisted. However, when I try to add a new purchase to a user, it seems to be attempting to create a new object with the same primary key 

Understood - the issue is the code you're using to update that user with a new purchase. We can help but need to see what that code looks like. Post it so we can spot the error.

I am pretty sure this is not a bug in Realm, just a implementation issue.

**Comment by igorsquadra-anoki** [comment] 2023-11-10 10:31
Here are my objects:
```swift
class User: Object {
  @Persisted(primaryKey: true) var id: Int
  @Persisted var purchases: List<Purchase>
}

class Purchase: EmbeddedObject {
  @Persisted(indexed: true) var id: Int
  @Persisted var book: Book?
  convenience init(
          from response: BookResponse.Purchase,
          withBook book: Book? = nil
   ) {
    self.init()

    id = response.id
    ... other stuff ..
    
    // Here is where the crash happens
    if let book {
      **self.book = book**
    }
   }
}

class Book: Object {
  @Persisted(primaryKey: true) var id: Int
}
```
Here is my func:

```swift
func saveBooks(from responses: [BookResponse], user: User) async throws {
    // Creating books from api response
    let books = responses.map { Book(from: $0) }
    // Save books to Realm (everything ok)
    for book in books {
        try await realm.asyncWrite {
            realm.add(object, update: update)
        }
    }

    // Creating purchases array
    var purchases = [Purchase]()
    for response in responses {
      let book = books.first { $0.id == response.id }
      purchases.append(contentsOf: response.purchases.map { purchase in
        // Init purchase object
        return **Purchase(from: purchase, withBook: book)**
      })
    }

    // Here is where the crash happens.
    try await realm.asyncWrite { 
      // Appending purchases array to user since Purchase is an EmbeddedObject
      **user.purchases.append(objectsIn: purchases)**
    }
}
``` 

The purchase contains a book already existing on db.
What's the best way to create a relation between an embedded object (Purchase) and an object (Book)

Thanks for your help!

**Comment by Jaycyn** [comment] 2023-11-10 19:09
1) Can you clarify this?

`let books = responses.map { Book(from: $0) }`

Realm objects don't have a `from` parameter and the `Book` Realm object doesn't define a `from:` so that needs some clarity


2) The use of uppercase `BookResponse.Purchase`... is a bit confusing. BookResponse is not defined in the question so we don't know what that is. Perhaps a class property?

3) Is the var `response` here

`from response: BookResponse.Purchase`

actually a response or is it a .Purchase?

4) This is odd

`realm.add(object, update: update)`

add.... object?

And the update parameter is either .all, .error or .modified

Perhaps it's supposed to be `realm.add(book, update: .modified)`

5) Then to the question

> What's the best way to create a relation between an embedded object (Purchase) and an object (Book)

There are many relationships and many ways to do that. It's fairly straightforward:

In it's simplest form, one way relationship is just adding a property that stores a reference to the 'other' object

```
class EmbeddedDog: Object {
    @Persisted var name = "Spot"
    @Persisted var related_person: Person!
}

class Person: Object {
   @Persisted var name = "Jay
}

let dog = EmbeddedDog()
let person = Person()

dog.related_person = jay

//then add dog to a List or a property of a class that is persisted and when written it will contain dog
```

Your code pretty much does that but with the above unknowns it's hard to troubleshoot and we can't duplicate the issue without a lot more clarity. It does *feel* like there are several places where a Books primaryKey could be assigned to another Book object (`let books = responses.map { Book(from: $0) }`) and then attempted to be written out which would throw the error you're seeing (duplicate primary key)

So - I suggest this issue is not a bug and the topic be closed as this forum is better suited for duplicatable bug reports. I think a better forum would be the [Realm SDK Forums](https://www.mongodb.com/community/forums/c/atlas-app-services-realm/realm/58) or even a question on [StackOverflow](www.stackoverflow.com).

However, before posting on either, the code needs clarity and the problem needs to be duplicatable - so a minimal example would be in order.

**Comment by igorsquadra-anoki** [comment] 2023-11-13 08:46
Let's use your example:
```swift
// I'm going to use an embedded object because a person can own multiple dogs
class EmbeddedDog: EmbeddedObject {
    @Persisted var name = "Spot"
    @Persisted var leash: Leash?

class Person: Object {
   @Persisted var name = "Jay"
   @Persisted var dogs: List<EmbeddedDog> // Based on Realm documentation it should be correct
}

// Let's add another object. **It's a dog leash so each dog has a direct relation with one leash.**
class Leash: Object {
   @Persisted var brand: Brand // We don't care about brand, it's just an example
}

// 
let person = Person(dogs: []) // Using empty array for example (just to initialize before appending object)
let myLeash = Leash(brand: MyBrand())
let myDog = EmbeddedDog(leash: myLeash) // Here I need to create the relation between dog and leash

try await realm.asyncWrite {
     realm.add(person, update: .modified) // It works well
     realm.add(myLeash, update: .modified) // It works well
     realm.add(myDog, update: .modified) // It works well
}

Here is the problem -> //then add dog to a List or a property of a class that is persisted and when written it will contain dog

try await realm.asyncWrite {
    person.dogs.append(myDog) // Crash here because `myLeash` object (embedded in myDog object) already exists and Realm is not able to update an existing object with same primary key. 
}
```
As you say it's straightforward, but I'm not able to find a real answer to this question.

The steps I need to follow are:
1. Create a person
2. Create a leash
3. Create a dog
4. **Add a relation between dog and leash** <-- That's my problem
5. Append dog to person's list of dogs

**Comment by Jaycyn** [comment] 2023-11-13 18:36
So here's part of the problem

```
class EmbeddedDog: EmbeddedObject {
    @Persisted(primaryKey: true) var id: String
```

Embedded objects cannot have primary keys because they are not managed objects.

Same thing here

`realm.add(myDog, update: .modified)`

It doesn't work because EmbeddedObjects are not added to Realm in that fashion because they are not managed objects

EmbeddedObjects ONLY EXIST as part of another object - hence 'embedded' - they become part of that objects data and do not exist outside that object.

Here's some example code

```
let person = Person()
person.name = "Jay"

let dog = EmbeddedDog()
dog.name = "Spot"

person.dogs.append(dog)

try! realm.write {
   realm.add(person)
}
```

The dog becomes part of the person (within the list) and not a reference to another object.

**Comment by igorsquadra-anoki** [comment] 2023-11-14 08:13
It doesn't work as simple Object too, but let's try in this way:

I have a person, a dog and a leash.
- The person has a list of dogs
- The dog has a reference to its leash (just one)

**How can I achieve this kind of relationship?**

**Comment by Jaycyn** [comment] 2023-11-14 19:49
The model structure will depend on what kinds of queries are run against the data. If the intention is that both the dog and the leash are embedded, this requirement is problematic:

> The dog has a reference to its leash (just one)

Because embedded objects are not references. They are actual data and do no exist outside of the parent object

If the objective is to have a managed object Person, with a list of embedded dogs and each embedded dog has an embedded leash, this will do it

Start with the models

```
class Person: Object {
    @Persisted var name = ""
    @Persisted var embeddedDogList = List<EmbeddedDog>()
}

class EmbeddedDog: EmbeddedObject {
    @Persisted var name = ""
    @Persisted var leash: EmbeddedLeash!
}

class EmbeddedLeash: EmbeddedObject {
    @Persisted var leashType = ""
}
```

then instantiate the three, embed the leash into the dog, and the dog into the person

```
let person = Person()
let dog = EmbeddedDog()
let leash = EmbeddedLeash()

person.name = "Jay"
dog.name = "Spot"
leash.leashType = "Sparkly"

dog.leash = leash //add the embedded leash to the dog

person.embeddedDogList = dog //add the embedded dog, which has an embedded leash to the person

try! realm.write {
   realm.add(person)
}
```

One of the big differences in Object and EmbeddedObjects is the Objects are used by reference, EmbeddedObjects are the actual data. Objects can be queried directly, embedded objects and only be queried through their parent object.

That makes Objects more versatile when the same object data will be used in multiple places. EmbeddedObject data cannot be re-used - it only exists on one place; in it's parent object.

Using the above, suppose a dog could belong to two people, like a husband and wife. If the dog was embedded, it would have to be added to the husbands dog list and then another instance of the dog would be added to the wifes list.

Suppose the dog got a new LED leash instead of the sparkly one.

If it was a managed object, the leash could be changed on the dog and that would be it. When embedded however, the leash would have to be updated on the husbands dog

`husbandPerson.dogList[dogIndex].leash = "LED"`

as well as the wifes dog

`wifePerson.dogList[dogIndex].leash = "LED"`

Then expand on that - what if the dog had 50 owners.. every one of the person objects would need to be updated. Whereas if the Dog was a Realm Object, just one update and its done.

**Comment by nirinchev** [comment] 2024-02-06 12:10
Closing this as seems to be mostly resolved (thank you, @Jaycyn!) and is more of a data-modeling question than an actual bug report. For future reference, questions like this are best suited to the forums.

**Closed by nirinchev** 2024-02-06 12:10 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Frequency:Always, Repro:Always, Encryption:Off
