### ISSUE TITLE
Create a circular object graph directly in one call

### ISSUE THREAD

**Issue by dumoko** [realm/realm-swift#1800] opened 2015-04-27 09:23 UTC
Hi.
I have a crash.

Info:
we have a several level structure.
Main model has several one-to-many and one-to-one relationships. Some of these models have also some relationships by their own.

Goal:
Copy the object with all its dependencies into a new realm.

Setup:
We have two realms, the default one, and the custom one.
We add the model to the default one, and then we need to copy it to the custom one.

```
RLMRealm *customRealm = [ModelClass customRealm];
[customRealm transactionWithBlock:^{
  [ModelClass createInRealm: customRealm withObject:model];
}];
```

Realm version: 0.91.1
Xcode: 6.3

Stack trace:
https://gist.github.com/OlegAnghelov/21949e98688f769825b1
Code crash:
[screenshot 2015-04-23 18 26 03](https://cloud.githubusercontent.com/assets/457094/7344836/2193d600-ecd8-11e4-8ad6-186be1b5ae16.png)

Or is there anything I am doing incorrectly in this situation? I can't find any hints in the documentation.

**Comment by OlegAnghelov** [comment] 2015-04-27 11:35
I created a custom project:

https://www.dropbox.com/s/d59derdr489a4nn/RealmMigration.zip?dl=0

**Comment by segiddins** [comment] 2015-04-27 19:44
@OlegAnghelov thanks so much for putting together this example project. The code path behind `createOrUpdate` is something that needs a good refactor (see https://github.com/realm/realm-cocoa/issues/1362), and that refactor should definitely address this issue. In the meantime, your best bet would be to not pass cyclical object graphs to `createInRealm` -- I know that's not ideal, but it should work as a stopgap while we fix the underlying issue.

**Comment by segiddins** [comment] 2015-04-27 23:13
The following is a failing unit test case that reproduces the issue:

```objc
- (void)testCreateInRealmWithCircularObject
{
    RLMRealm *realm = [self realmWithTestPath];

    CircleObject *object = [[CircleObject alloc] init];
    object.data = @"data";
    object.next = [[CircleObject alloc] initWithObject:@[@"other data", object]];

    [realm beginWriteTransaction];
    [CircleObject createInRealm:realm withObject:object];
    [realm commitWriteTransaction];
}
```

**Comment by jpsim** [comment] 2015-12-10 21:12
I've demoted this from P1 to P2 because we've had very few requests for this and we believe our other P1s are higher priorities.

**Comment by cday** [comment] 2016-03-07 10:04
Would like to request this given that any kind of follower/following relationship cannot be shared between Realms without a fix for this.

**Comment by JadenGeller** [comment] 2016-06-28 20:48
Unassigned because it's not clear that this is a direction we want to head. It creates an unnecessary space overhead for acyclic graphs, and it seems to encourage use cases where the user works with their objects outside of Realm and repeatedly copies them into Realm.

@dumoko It would be useful to know why you'd like to copy this object graph into Realm rather than using the `add` function.

**Closed** 2022-03-21 17:50 UTC
Labels: T-Enhancement, O-Community
