### ISSUE TITLE
Name collision with SwiftUI

### ISSUE THREAD

**Issue by progalgo** [realm/realm-swift#8284] opened 2023-06-25 23:45 UTC
https://github.com/realm/realm-swift/blob/8f5f6d0863bad30f76753a32523321a8885e8db9/RealmSwift/App.swift#L169

Also, who names such things with word "App"? Following such logic we should call NTFS an operating system, and mouse driver a window system. Such misnomers become a huge barrier to people new to programming, and they also make writing code harder for experienced developers.

I believe, this API should be changed. A word "Backend" or "Database" would be somewhat better.

**Comment by leemaguire** [comment] 2023-06-26 08:28
Closing as duplicate of https://github.com/realm/realm-swift/discussions/8283

**Closed** 2023-06-26 08:29 UTC
Labels: O-Community
