### ISSUE TITLE
realm.object returns nil when overriding primary key

### ISSUE THREAD

**Issue by ljoraanstad** [realm/realm-swift#7967] opened 2022-09-21 17:28 UTC
### How frequently does the bug occur?

All the time

### Description

It seems that [Issue #6672](https://github.com/realm/realm-swift/issues/6672) is still an active issue in the latest version of RealmSwift.

When defining a class or model, and using the `override class func primaryKey() -> String?` function to override the primary key, it would seem that RealmSwift's `realm.object(ofType: ..., forPrimaryKey: ...)` returns nil when trying to access the object. I have confirmed the object exists in Realm through a test of replacing `realm.object` with `realm.objects(...).filter(...)` which successfully retrieves the object.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

* Create a model with some defined properties
* Override the primary key
* Attempt to retrieve a written object using realm.object
* Observe nil result

### Version

10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16.0

### Build environment

Current Version of RealmSwift: 10.29.0 
X-Code Version: 14.0
Swift Version: 16.0

**Comment by dianaafanador3** [comment] 2022-09-22 11:08
HI @ljoraanstad It would be helpful if I you can copy your object model code, because a simple test with a test object and a string primary key seems like it is working fine.
Also have you tried to migrate to our new model declaration syntax https://www.mongodb.com/docs/realm/sdk/swift/model-data/define-model/object-models/, you can test with this as well and check if there are any discrepancies between the two declarations.

**Comment by ljoraanstad** [comment] 2022-09-22 15:50
@dianaafanador3 Here is an example model:

```
class ModelUpdateEvent: BaseObjectMapper {
    @objc dynamic var command: String?
    @objc dynamic var model_uuid: String?
    @objc dynamic var name: String?
    @objc dynamic var value: String?
    @objc dynamic var version: String?
    @objc dynamic var version_new: String?
    @objc dynamic var carrier_uuid: String?
    @objc dynamic var occurred_at: String? = DateFormatter.string(from: Date(), with: .iso8602)
    @objc dynamic var duplicated_from_uuid: String?
    @objc dynamic var meta: ModelUpdateMeta?
    var events = List<ModelUpdateEvent>()
    @objc dynamic var parentId: String?

    required convenience init?(map: ObjectMapper.Map) {
        self.init()
    }
    
    override class func primaryKey() -> String? {
        return "version_new"
    }
    
    override func mapping(map: ObjectMapper.Map) {
        map.shouldIncludeNilValues = true
        command <- map["command"]
        model_uuid <- map["model_uuid"]
        name <- map["name"]
        version <- map["version"]
        value <- map["value"]
        occurred_at <- map["occurred_at"]
        carrier_uuid <- map["carrier_uuid"]
        duplicated_from_uuid <- map["duplicated_from_uuid"]
        meta <- map["meta"]
        events <- (map["events"], ListTransform<ModelUpdateEvent>())

        if map.mappingType == .fromJSON {
            version_new <- map["version_new"]
        } else {
            version_new >>> map["version_new"]
        }
        
    }
}
```

**Comment by dianaafanador3** [comment] 2022-09-22 17:00
Did you test using `@Persited` property wrapper?, can you also attach the code where you are retrieving the object from the primary key and the code for the filtering

**Comment by ljoraanstad** [comment] 2022-09-22 17:10
@dianaafanador3 
```
    private func attachedObjects<T: Object>(_ objects: [T]) -> [T] {
        var attachedObjects = objects.filter({ $0.isInvalidated == false && $0.realm != nil })
        let detachedObjects = objects.filter({ $0.isInvalidated == true || $0.realm == nil })
        
        //Attempt to add all detached objects
        for detachedObject in detachedObjects {
            guard let staticPrimaryKey = detachedObject.superclass?.primaryKey() else { print("WARNING: Primary key missing. Can't remove detached realm object."); continue }
            let mirror = Mirror(reflecting: detachedObject)
            let primaryKeyValue = retrieveValue(forKey: staticPrimaryKey, mirror: mirror)
            if let object = realm.objects(mirror.subjectType as! Object.Type).filter(NSPredicate(format: "\(staticPrimaryKey) == %@", primaryKeyValue as! String)).first as? T {
                attachedObjects.append(object)
            } else {
                print("Unable to retrieve object \(detachedObject)")
            }
        }
        return attachedObjects
    }
```

This is the current working code. Previously, it was  

`            if let object = realm.object(ofType: mirror.subjectType as! Object.Type, forPrimaryKey: primaryKeyValue) as? T `

I did not try with the @Persisted property wrapper yet. I can give that a try.

**Comment by dianaafanador3** [comment] 2022-09-22 17:59
@ljoraanstad I tested the following test and everything seems to be working fine, seems like something very particular to your data model and you implementation
```
func test() throws {
        let uuid = UUID().uuidString
        let realm = try Realm()
        let object = SwiftPrimaryStringObject()
        object.stringCol = uuid
        object.intCol = 333
        try realm.write {
            realm.add(object)
        }

        let foundObject = realm.object(ofType: SwiftPrimaryStringObject.self, forPrimaryKey: uuid)
        XCTAssertEqual(foundObject!.stringCol, uuid)
        XCTAssertEqual(foundObject!.intCol, 333)

        let filteredObjects = realm.objects(SwiftPrimaryStringObject.self).where { $0.stringCol == uuid }
        XCTAssertEqual(filteredObjects.count, 1)
        XCTAssertEqual(filteredObjects.first!.stringCol, uuid)
        XCTAssertEqual(filteredObjects.first!.intCol, 333)

       // Test passes
        let newFoundObject: SwiftPrimaryStringObject = findObject(object, for: realm)
        XCTAssertEqual(newFoundObject.stringCol, uuid)
        XCTAssertEqual(newFoundObject.intCol, 333)
    }

    private func findObject<T: Object>(_ object: T, for realm: Realm) -> T {
        guard let staticPrimaryKey =  object.superclass?.primaryKey() else {
            print("WARNING: Primary key missing. Can't remove detached realm object.")
            fatalError()
        }

        let mirror = Mirror(reflecting: object)
        var primaryKey: String = ""
        mirror.children.forEach { child in
            if child.0 == staticPrimaryKey {
                primaryKey = child.1 as! String
            }
        }

        if let object = realm.object(ofType: mirror.subjectType as! Object.Type, forPrimaryKey: primaryKey) as? T {
            return object
        } else {
            print("Unable to retrieve object \(object)")
            fatalError()
        }
    }
```
This happens for all the objects passed to `attachedObjects`?
The only particular think I see is that your model inherit from `BaseObjectMapper` which could be affecting the Type obtained from the reflection. 
Both function have different implementation which could mean why one may work and the the other not.
If you can provide a sample project where I can reproduce this, that would be pretty helpful.

**Comment by leemaguire** [comment] 2022-11-10 15:46
@ljoraanstad did you manage to resolve your issue?

**Comment by dianaafanador3** [comment] 2023-01-04 17:41
Closing this as there is no answer from the user, and seems related to their particular implementation.

**Closed by dianaafanador3** 2023-01-04 17:41 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter
