### ISSUE TITLE
Terminating with uncaught exception of type realm::util::DecryptionFailed: Decryption failed

### ISSUE THREAD

**Issue by reggian** [realm/realm-swift#7725] opened 2022-03-29 11:55 UTC
### How frequently does the bug occur?

Sometimes

### Description

We have been seeing Decryption failed crashes in the wild, but never could get a corrupted realm file in house, until now.
What led to a corrupted realm file I do not really know. But the crash occurs when trying to open the realm file.

### Stacktrace & log output

```shell
terminating with uncaught exception of type realm::util::DecryptionFailed: Decryption failed
Exception backtrace:
0   Realm                               0x00000001043d5c58 _ZN5realm4util16DecryptionFailedC2Ev + 100
1   Realm                               0x00000001043bf030 _ZN5realm4util10AESCryptor4readEixPcm + 440
2   Realm                               0x00000001043bfbbc _ZN5realm4util20EncryptedFileMapping12refresh_pageEm + 108
3   Realm                               0x00000001043c0580 _ZN5realm4util20EncryptedFileMapping12read_barrierEPKvmPFmPKcE + 128
4   Realm                               0x0000000103f2a398 _ZN5realm4util26do_encryption_read_barrierEPKvmPFmPKcEPNS0_20EncryptedFileMappingE + 68
5   Realm                               0x0000000104236268 _ZNK5realm9Allocator23translate_less_criticalEPNS0_14RefTranslationEm + 324
6   Realm                               0x0000000103f2a090 _ZNK5realm9Allocator18translate_criticalEPNS0_14RefTranslationEm + 252
7   Realm                               0x0000000103f29ef0 _ZNK5realm9Allocator9translateEm + 72
8   Realm                               0x0000000103f29e68 _ZN5realm5Array13init_from_refEm + 40
9   Realm                               0x000000010428ec64 _ZN5realm5Group6attachEmbb + 128
10  Realm                               0x0000000104278b2c _ZN5realm11TransactionC2ENSt3__110shared_ptrINS_2DBEEEPNS_9SlabAllocERNS3_12ReadLockInfoENS3_13TransactStageE + 432
11  Realm                               0x000000010427855c _ZN12_GLOBAL__N_120make_transaction_refIJNSt3__110shared_ptrIN5realm2DBEEEPNS3_9SlabAllocERNS4_12ReadLockInfoENS4_13TransactStageEEEENS2_INS3_11TransactionEEEDpOT_ + 92
12  Realm                               0x0000000104274628 _ZN5realm2DB11start_writeEb + 248
13  Realm                               0x00000001044a3868 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1748
14  Realm                               0x00000001044a45a4 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 72
15  Realm                               0x00000001044a43c8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 400
16  Realm                               0x0000000104538ed4 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 120
17  Realm                               0x00000001041969a0 +[RLMRealm realmWithConfiguration:queue:error:] + 1768
18  Realm                               0x0000000104196260 +[RLMRealm realmWithConfiguration:error:] + 88
...
```

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000021961ab78 in __pthread_kill ()
#1	0x000000025328c3bc in pthread_kill ()
#2	0x00000001ecc3451c in abort ()
#3	0x00000001fa8c1b7c in abort_message ()
#4	0x00000001fa8b19ac in demangling_terminate_handler() ()
#5	0x00000001fa7bcc98 in _objc_terminate() ()
#6	0x00000001fa8c0f18 in std::__terminate(void (*)()) ()
#7	0x00000001fa8c0eb4 in std::terminate() ()
#8	0x0000000103f238c0 in __clang_call_terminate ()
#9	0x00000001042362f4 in realm::Allocator::translate_less_critical(realm::Allocator::RefTranslation*, unsigned long) const ()
#10	0x0000000103f2a090 in realm::Allocator::translate_critical(realm::Allocator::RefTranslation*, unsigned long) const at .../Build/Products/Debug-iphoneos/XCFrameworkIntermediates/Realm/Headers/realm/alloc.hpp:587
#11	0x0000000103f29ef0 in realm::Allocator::translate(unsigned long) const at .../Build/Products/Debug-iphoneos/XCFrameworkIntermediates/Realm/Headers/realm/alloc.hpp:598
#12	0x0000000103f29e68 in realm::Array::init_from_ref(unsigned long) at .../Build/Products/Debug-iphoneos/XCFrameworkIntermediates/Realm/Headers/realm/array.hpp:118
#13	0x000000010428ec64 in realm::Group::attach(unsigned long, bool, bool) ()
#14	0x0000000104278b2c in realm::Transaction::Transaction(std::__1::shared_ptr<realm::DB>, realm::SlabAlloc*, realm::DB::ReadLockInfo&, realm::DB::TransactStage) ()
#15	0x000000010427855c in std::__1::shared_ptr<realm::Transaction> (anonymous namespace)::make_transaction_ref<std::__1::shared_ptr<realm::DB>, realm::SlabAlloc*, realm::DB::ReadLockInfo&, realm::DB::TransactStage>(std::__1::shared_ptr<realm::DB>&&, realm::SlabAlloc*&&, realm::DB::ReadLockInfo&, realm::DB::TransactStage&&) ()
#16	0x0000000104274628 in realm::DB::start_write(bool) ()
#17	0x00000001044a3868 in realm::_impl::RealmCoordinator::open_db() ()
#18	0x00000001044a45a4 in realm::_impl::RealmCoordinator::do_get_realm(realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) ()
#19	0x00000001044a43c8 in realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>) ()
#20	0x0000000104538ed4 in realm::Realm::get_shared_realm(realm::Realm::Config) ()
#21	0x00000001041969a0 in +[RLMRealm realmWithConfiguration:queue:error:] at .../Pods/Realm/Realm/RLMRealm.mm:477
#22	0x0000000104196260 in +[RLMRealm realmWithConfiguration:error:] at .../Pods/Realm/Realm/RLMRealm.mm:399
...
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

I have a corrupted realm file, but it has user data in it which I wish I would not share.

### Version

10.22.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15.4

### Build environment

```
ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230

/Applications/Xcode.app/Contents/Developer
Xcode 13.3
Build version 13E113

/opt/homebrew/bin/pod
1.11.3
Realm (10.22.0)
Realm (= 10.22.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

/opt/homebrew/bin/carthage
0.38.0
(not in use here)

/usr/bin/git
git version 2.32.0 (Apple Git-132)
```

**Comment by pavel-ship-it** [comment] 2022-03-29 16:47
Hi @reggian,
Is it happening for newly created Realm file?
Is it involving a migration of Realm version, schema version?
If it's fine you can share the sample file with me via email (pavel.yakimenko@mongodb.com)

**Comment by reggian** [comment] 2022-03-29 19:41
Hi @pavel-ship-it, thank you for looking into this.

>Is it happening for newly created Realm file?

No, newly created Realm file works perfectly fine.

>Is it involving a migration of Realm version, schema version?

Could be, since this person does not have automatic updates enabled on their phone.
The Realm version was updated two updates ago (four weeks ago)
The schema version was updated three updates ago (five weeks ago).
But I really can't say for certain.

>If it's fine you can share the sample file with me via email 

If it is possible I would try to avoid this until there is no other option (and even then I need to acquire the user's consent first). Can you deduce something from the Realm file without the encryption key?

Unfortunately I don't know the steps how the realm got corrupted.
If it helps, we do access the Realm from different threads and wrap every transaction in an autoreleasepool block.

**Comment by zane-carter** [comment] 2022-03-31 02:44
This may be a duplicate of: https://github.com/realm/realm-swift/issues/7717
I am also experiencing this issue with similar logs.

**Comment by pavel-ship-it** [comment] 2022-04-12 10:58
@reggian, @emtjoshhart,
This issue should be fixed in Realm v10.25.1
Please let us know if you still see the problem.

**Comment by mxsc** [comment] 2022-04-26 07:27
we seem to get the same issue, even after bumping to 10.25.1.

**Comment by ericjordanmossman** [comment] 2022-04-26 19:00
@mxsc Does this occur on realm files which were created after upgrading to 10.25.1? If the realm files were created in an earlier version, you may need to reinstall the application.

**Comment by ericjordanmossman** [comment] 2022-04-28 18:43
Similar to [this thread](https://github.com/realm/realm-swift/issues/7717#issuecomment-1110154404).
10.25.1 can only prevent newly created realm files from entering a bad state.

**Comment by pavel-ship-it** [comment] 2022-05-24 15:47
Ok, it looks like the original issue has been fixed and I'm closing the ticket.

**Closed by pavel-ship-it** 2022-05-24 15:47 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter
