### ISSUE TITLE
Repeative Crash 

### ISSUE THREAD

**Issue by GengJian** [realm/realm-swift#8491] opened 2024-02-19 10:10 UTC
### How frequently does the bug occur?

Always

### Description

![image](https://github.com/realm/realm-swift/assets/13254245/ab6119fb-11e3-4e6b-954d-7a6e05ff596b)

When I upgraded the version from - Realm (10.32.3). to - Realm (10.43.1). begin crash

Crashed: io.realm.asyncOpenDispatchQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000059

### Stacktrace & log output

```shell
Crashed: io.realm.asyncOpenDispatchQueue
0  libobjc.A.dylib                0x1aa28 class_getSuperclass + 4
1  Realm                          0x5aa98 RLMIsObjectSubclass + 20
2  Realm                          0x136304 RLMRegisterClassLocalNames(objc_class**, unsigned long) + 88
3  Realm                          0x136a00 +[RLMSchema sharedSchema] + 104
4  Realm                          0x127a50 +[RLMRealm realmWithConfiguration:confinedTo:error:] + 1392
5  Realm                          0x2353c -[RLMAsyncOpenTask downloadCompleted] + 144
6  Realm                          0x23130 -[RLMAsyncOpenTask startAsyncOpen] + 144
7  Realm                          0x23090 __39-[RLMAsyncOpenTask waitWithCompletion:]_block_invoke + 32
8  libdispatch.dylib              0x26a8 <redacted> + 32
9  libdispatch.dylib              0x4300 <redacted> + 20
10 libdispatch.dylib              0x77b8 <redacted> + 600
11 libdispatch.dylib              0x6dd4 <redacted> + 584
12 libdispatch.dylib              0x15be4 <redacted> + 392
13 libdispatch.dylib              0x163ec <redacted> + 156
14 libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
15 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

### Can you reproduce the bug?

Always

### Version

10.45.3

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 14 - iOS 17

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by Jaycyn** [comment] 2024-02-19 17:48
Can you please provide a minimal but complete coding sample that replicates the crash?

**Comment by GengJian** [comment] 2024-02-20 01:12
#if DEBUG
    private static let realmName = "localDB.realm"
#else
    private static let realmName = "defaultDB.realm"
#endif

func initDefaultConfig() {
        guard let documentsURL = FileManager.default.urls(
            for: .documentDirectory,
            in: .userDomainMask
        ).first else {
            return
        }

        let dbPath = documentsURL.appendingPathComponent(realmName)
        let config = Realm.Configuration(
            fileURL: dbPath,
            schemaVersion: 3
        ) { migration, oldSchemaVersion in
            if oldSchemaVersion < 2 {
                migration.enumerateObjects(ofType: VSTempHumiRecord.className()) { oldObject, newObject in
                    newObject?.inTemp = oldObject?.inTemp
                    newObject?.outTemp = oldObject?.outTemp
                    newObject?.inHumi = oldObject?.inHumi
                    newObject?.outHumi = oldObject?.outHumi
                    if oldObject?.isSynced == nil {
                        newObject?.isSynced = false
                    }
                }
            }

            if oldSchemaVersion < 3 {
                migration.enumerateObjects(ofType: VSTempHumiRecord.className()) { oldObject, newObject in
                    newObject?.bTemp = oldObject?.inTemp
                    newObject?.bHumi = oldObject?.inHumi
                    newObject?.pTemp = oldObject?.outTemp
                    newObject?.pHumi = oldObject?.outHumi
                }
            }
        }
        Realm.Configuration.defaultConfiguration = config
        Realm.asyncOpen { result in
            switch result {
            case .success(let realm):
                print(self, realm)
            case .failure(let error):
                print(self, error)
            }
        }
    }

**Comment by GengJian** [comment] 2024-02-20 01:19
public class VSTempHumiRecord: Object {
    @Persisted(primaryKey: true) var unionPrimaryKey: String = ""
    @Persisted var showDate: Date?
    @Persisted var cFanlv: Int?
    @Persisted var dFanlv: Int?
    @Persisted var lightlv: Int?
    @Persisted var inHumi: Int? = 0
    @Persisted var inTemp: Int? = 0
    @Persisted var outHumi: Int? = 0
    @Persisted var outTemp: Int? = 0
    @Persisted var bHumi: Int?
    @Persisted var bTemp: Int?
    @Persisted var pHumi: Int?
    @Persisted var pTemp: Int?
    @Persisted var time = 0
    @Persisted var deviceId = ""
    @Persisted var isSynced = false
}

**Comment by nirinchev** [comment] 2024-02-20 11:58
I have tried to copy your code in a brand new project, ran it, and didn't get any crashes. You can find the project I used attached to this comment. If you're able to modify the project I supplied or provide us with a project that actually reproduces the problem, we'll be able to continue the investigation.

[Issue8491-ios.zip](https://github.com/realm/realm-swift/files/14343908/Issue8491-ios.zip)

**Comment by GengJian** [comment] 2024-02-23 08:33
It may be that in the demo there is no historical data so there will be no time-consuming operation.

However, in the specific project( on-line release version), our firebase crashlytics in general prompts are triggered within 1-2s of app startup. 

So I would like to ask the crash caused by initialization migration operation ```initDefaultConfig``` written in ```appdelegate. didFinshLaunching```？

**Comment by Jaycyn** [comment] 2024-02-23 14:05
When you add a breakpoint to your code, and then run the project and step through it line by line, what line is crashing? Which variables are not as expected?

**Comment by nirinchev** [comment] 2024-02-23 15:41
@GengJian it may very well be the historical data on the device, but unless we're able to repro the crash or get more information about it, there's not much we can do. My point was that I tried to repro with the code you provided and things work correctly for me. If you're able to give us more details or a repro case we can run locally, then I'd be happy to continue investigating.

**Comment by nirinchev** [comment] 2024-03-10 00:54
A similar crash report can be found here https://github.com/realm/realm-swift/issues/5618 where the issue appears to be caused by FirebasePerformance. There are several workarounds suggested there, notably rather than rely on automatic schema discovery, you can explicitly specify the `objectClasses` field in your configuration.

I'll close the issue due to lack of information, but if you do come back to it and keep seeing it after trying the suggested workarounds, feel free to reopen.

**Closed by nirinchev** 2024-03-10 00:54 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, SDK-Use:Local, Frequency:Always, Repro:Always, Encryption:Off
