### ISSUE TITLE
new project, use cocoapods install realm, error: 'Realm/Realm.h' file not found

### ISSUE THREAD

**Issue by zhangfurun** [realm/realm-swift#7800] opened 2022-05-18 14:08 UTC
### How frequently does the bug occur?

All the time

### Description

xcode Version 13.3.1 (13E500a)
cocoadpos : 1.11.3

create new project, then `pod init` and `pod 'Realm', '~>10'`

PodFile: 

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmTest

  target 'RealmTestTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Realm', '~>10'
  end

  target 'RealmTestUITests' do
    # Pods for testing
pod 'Realm', '~>10'
  end

end


```

so, pod success, then, in ViewController 

```
#import "ViewController.h"

#include <Realm/Realm.h>

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}


@end
```
error: 
'Realm/Realm.h' file not found

### Can you reproduce the bug?

Yes, always

### Version

10.25.2 and  5.5.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac12.3.1 

### Build environment

Xcode version: 13.3.1 
Dependency manager and version: ...

**Comment by ericjordanmossman** [comment] 2022-05-19 16:53
@zhangfurun 
I'm unable to reproduce myself. First thing to try is deleting /Pods, the reinstall with `pod install --repo-update`. Then clean and build.

**Comment by dianaafanador3** [comment] 2022-07-01 16:18
HI @zhangfurun are you still having this issue?, if that not the case please close this issue

**Comment by leemaguire** [comment] 2022-08-26 11:54
Closing as no response from user and not reproducible.

**Closed** 2022-08-26 11:54 UTC
Labels: T-Bug, O-Community, More-information-needed, Waiting-For-Reporter
