### ISSUE TITLE
try await Realm() creates invalid Realm instances when targeting Swift 5.7 (Xcode14)

### ISSUE THREAD

**Issue by tylerjdoyle** [realm/realm-swift#7844] opened 2022-06-14 20:05 UTC
### How frequently does the bug occur?
All the time

### Description
Realm forces an `await` when creating a `Realm` instance in an async code block. Using that realm instance causes an error when verifying. Seem to work fine when built from Xcode 13 (Swift 5.6)

### Stacktrace & log output
```shell
- 0 : "0   ???                                 0x0000000104a5caf0 0x0 + 4372941552"
  - 1 : "1   RealmAsyncSample                    0x0000000104433114 main + 0"
  - 2 : "2   libunwind.dylib                     0x00000001f0b6f4f8 _Unwind_RaiseException + 400"
  - 3 : "3   libc++abi.dylib                     0x0000000199374c00 __cxa_throw + 132"
  - 4 : "4   libobjc.A.dylib                     0x000000019926ae88 objc_exception_throw + 352"
  - 5 : "5   Realm                               0x0000000105c2d1b4 -[RLMRealm verifyThread] + 124"
  - 6 : "6   Realm                               0x0000000105ac1478 _ZL18RLMVerifyRealmReadP8RLMRealm + 68"
  - 7 : "7   Realm                               0x0000000105ac2e58 RLMGetObject + 88"
  - 8 : "8   RealmSwift                          0x0000000104c8eb34 $s10RealmSwift0A0V6object6ofType13forPrimaryKeyxSgxm_q_tSo0aB6ObjectCRbzr0_lF + 464"
  - 9 : "9   RealmAsyncSample                    0x0000000104431628 $s16RealmAsyncSample16ContentViewModelC9realmTest33_7579262021964CED0CD837BF1168C972LLyyYaKFTY2_ + 164"
  - 10 : "10  RealmAsyncSample                    0x0000000104430ff5 $s16RealmAsyncSample16ContentViewModelCACycfcyyYaYbcfU_TQ0_ + 1"
  - 11 : "11  RealmAsyncSample                    0x00000001044311bd $s16RealmAsyncSample16ContentViewModelCACycfcyyYaYbcfU_TATQ0_ + 1"
  - 12 : "12  RealmAsyncSample                    0x000000010443219d $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTQ0_ + 1"
  - 13 : "13  RealmAsyncSample                    0x0000000104432489 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTATQ0_ + 1"
  - 14 : "14  libswift_Concurrency.dylib          0x00000001fccd90bd 6C799FB1-8896-35F6-B6D4-C5A219C2E8CD + 274621"
```

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
1. Create a sample project and install Realm using pod install
1. Create an async function similar to:

```swift
class Sample {
   static func realmTest() async throws {
        let realm = try await Realm()
        let obj = realm.object(ofType: SampleObj.self, forPrimaryKey: 0)
        if let obj {
            print("Made it! \(obj)")
        }
    }
}

class SampleObj: Object {
    @Persisted(primaryKey: true) var id: Int
}
```

1. Call function in an async capacity

```swift
Task {
    do {
        try await Sample.realmTest()
    } catch {}
}
```

1. Run and observe the crash

### Version
10.28.1

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
MacOS Ventura 13

### Build environment
Xcode version: 14beta
Dependency manager and version: Cocoapods 1.11.3

**Comment by tgoyne** [comment] 2022-06-14 20:12
Duplicate of #7737.

The current implementation of async init is only usable in `@MainActor` functions. You also almost certainly don't actually want the async initializer anyway, but Swift ended up making it awkward to call the non-async one from an async function.

**Closed by tgoyne** 2022-06-14 20:12 UTC
Labels: T-Bug, O-Community
