### ISSUE TITLE
Floating crash in -[RLMRealm cancelWriteTransaction]

### ISSUE THREAD

**Issue by alexeyn-martynov** [realm/realm-swift#8235] opened 2023-05-16 16:02 UTC
### How frequently does the bug occur?

Sometimes

### Description

The application crashes due to an `RLMException` thrown in the `-[RLMRealm cancelWriteTransaction]` method. All crashes occur on the end-user side and are collected by Crashlytics. I have been unable to reproduce any of these crashes as they are relatively rare.

**Here is a typical stack trace from Crashlytics:**
```
Fatal Exception: RLMException
Realm accessed from incorrect thread.

Fatal Exception: RLMException
0  CoreFoundation                 0x9d94 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  MyApp                          0x11e9298 -[RLMRealm cancelWriteTransaction] + 618 (RLMRealm.mm:618)
3  MyApp                          0x11e9a90 -[RLMRealm dealloc] + 783 (RLMRealm.mm:783)
4  libobjc.A.dylib                0x21d4 AutoreleasePoolPage::releaseUntil(objc_object**)
5  libobjc.A.dylib                0x5bdc objc_autoreleasePoolPop
6  MyApp                          0x11e7ab0 +[RLMRealm realmWithConfiguration:confinedTo:error:] + 385 (RLMRealm.mm:385)
7  MyApp                          0x11e7554 +[RLMRealm realmWithConfiguration:queue:error:] + 331 (RLMRealm.mm:331)
8  MyApp                          0x1288c5c @nonobjc RLMRealm.__allocating_init(configuration:queue:) (<compiler-generated>)
9  MyApp                          0x1289124 Realm.init(configuration:queue:) + 93 (Realm.swift:93)
10 MyApp                          0xfcbf9c RealmManager.getRealm()
... ... ... ...
18 Foundation                     0x3c5c8 -[NSOperation start]
... ... ... ...
28 libsystem_pthread.dylib        0xb7c start_wqthread
```
Note: I have edited it to conceal confidential information.

**Here is information about all crashes:**
* All crashes are caused by an `RLMException Realm accessed from incorrect thread` thrown in `-[RLMRealm cancelWriteTransaction] + 618 (RLMRealm.mm:618)`.
* This exception can be thrown on both the main thread and background thread.
* The iOS versions affected range from 15.5.0 to 16.4.1.

**Reproduction Attempts**
All crashes are collected by Crashlytics. I have attempted to reproduce the issue by manipulating the app's state in lldb. I tried to replicate the crash using the following approach:
* Let's assume there is a background thread writing some data, and the main thread reading data. The background thread starts first and opens `RLMRealm` (let's call it 1). Then the main thread tries to open its own `RLMRealm` (let's call it 2).
* The main thread calls the `+[RLMRealm realmWithConfiguration:]` method, followed by checking the cached version of `RLMRealm` using the `RLMGetAnyCachedRealmForPath` call inside an `@autoreleasepool` block.
* Meanwhile, as the main thread works inside the `@autoreleasepool` block, the background thread finishes its work and releases the last strong reference to realm 1.
* Upon the completion of the `@autoreleasepool` block in the main thread, the `dealloc` for realm 1 is called. However, it is called on the main thread, not on the thread where the realm was created. I'm not entirely certain if this is an issue.

But what I don't understand is how `_realm->is_in_transaction()` can be true in the `-[RLMRealm dealloc]` method.
```
- (void)dealloc {
    if (_realm) {
        if (_realm->is_in_transaction()) {
            [self cancelWriteTransaction];
            NSLog(@"WARNING: An RLMRealm instance was deallocated during a write transaction and all "
                  "pending changes have been rolled back. Make sure to retain a reference to the "
                  "RLMRealm for the duration of the write transaction.");
        }
    }
}
```

**Please find the sample code attached. To emulate a crash on the iPhone simulator, follow these steps:**
1. Set a breakpoint on line `392` in the file `RLMRealm.mm`, where `realmIsCached = true;` is located (Realm version is 10.39.1). Configure the breakpoint with the condition `[NSThread isMainThread]` and the action `po [NSThread sleepForTimeInterval:15.0]`. This action will wait until the background thread releases the cached realm that is used by the main thread inside the `@autoreleasepool`.
![1_set_breakpoint_1](https://github.com/realm/realm-swift/assets/11162178/45960188-1f04-4c87-bf6b-98e61ff2cfb9)
3. Set a breakpoint on line 808 in the file `RLMRealm.mm`, where the condition `if (_realm->is_in_transaction())` is checked.
![2_set_breakpoint_2](https://github.com/realm/realm-swift/assets/11162178/f994cda8-9203-483d-aa0d-843d794923d5)
5. Once breakpoint 2 is hit, you can change a register so that the condition `_realm->is_in_transaction()` becomes `true`. Use the command `register write $rdi 1` to change the register. Please note that the register may vary. This is state manipulation, not a bug reproduction. I have no idea how execution can go this way in real app.
![3_modify_condition](https://github.com/realm/realm-swift/assets/11162178/dff439ad-9fe9-4ea1-a51b-8b3f5a4920a9)

Sorry for long description. Any help or hints would be really appreciated. Thank you!
[ViewController.swift.zip](https://github.com/realm/realm-swift/files/11489757/ViewController.swift.zip)

### Stacktrace & log output

```shell
Fatal Exception: RLMException
Realm accessed from incorrect thread.

Fatal Exception: RLMException
0  CoreFoundation                 0x9d94 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  MyApp                          0x11e9298 -[RLMRealm cancelWriteTransaction] + 618 (RLMRealm.mm:618)
3  MyApp                          0x11e9a90 -[RLMRealm dealloc] + 783 (RLMRealm.mm:783)
4  libobjc.A.dylib                0x21d4 AutoreleasePoolPage::releaseUntil(objc_object**)
5  libobjc.A.dylib                0x5bdc objc_autoreleasePoolPop
6  MyApp                          0x11e7ab0 +[RLMRealm realmWithConfiguration:confinedTo:error:] + 385 (RLMRealm.mm:385)
7  MyApp                          0x11e7554 +[RLMRealm realmWithConfiguration:queue:error:] + 331 (RLMRealm.mm:331)
8  MyApp                          0x1288c5c @nonobjc RLMRealm.__allocating_init(configuration:queue:) (<compiler-generated>)
9  MyApp                          0x1289124 Realm.init(configuration:queue:) + 93 (Realm.swift:93)
10 MyApp                          0xfcbf9c RealmManager.getRealm()
... ... ... ...
18 Foundation                     0x3c5c8 -[NSOperation start]
... ... ... ...
28 libsystem_pthread.dylib        0xb7c start_wqthread
```

### Can you reproduce the bug?

No

### Version

10.37.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.4.1

### Build environment

Xcode version: 14.2 (14C18)
Dependency manager and version: SPM, 5.3

**Comment by dianaafanador3** [comment] 2023-05-23 16:16
HI @alexeyn-martynov you're right, if you are committing the changes after a write, this should not be happening. 
Are you using a write block to do the writes, or are you using our `begingWrite` and `commitWrite` API?
Can you please share the code when you call `RealmManager.getRealm()` and where the realm get deallocated, maybe we can get more information to reproduce the issue.

**Comment by alexeyn-martynov** [comment] 2023-05-25 19:44
Hi @dianaafanador3, thank you for your response.
I am using the `beginWrite` and `commitWrite` methods. Here is the code I am currently using to save data on the background thread:
```
static func saveUserProfile(_ data: [String: Any]) throws -> UserProfile {
    let configuration = ...
    let realm = try Realm(configuration: configuration)
    
    var user: UserProfile!

    let needBeginTransaction = !realm.isInWriteTransaction
    if needBeginTransaction {
        realm.beginWrite()
    }
    
    let id = data["id"] as? NSNumber
    user = realm.create(UserProfile.self, value: ["id": id], update: .modified)

    // Updating UserProfile properties

    if needBeginTransaction {
        try realm.commitWrite()
    }
    
    return user
}
```

**Comment by dianaafanador3** [comment] 2023-05-31 10:31
any reason you are not doing this in a block? Doing this on a block will guarantee for the write to be committed after finishing doing all the transactions within the block, and you will not have the errors you are experiencing, which may be caused because the `realm.commitWrite()` is not been executed, and the de-allocation happening on a different thread.
Something like this:
``` swift
   static func saveUserProfile(_ data: [String: Any]) throws -> UserProfile {
        let configuration = Realm.Configuration()
        let realm = try Realm(configuration: configuration)

        var user: UserProfile!
        let id = data["id"] as? NSNumber
        try realm.write {
            user = realm.create(UserProfile.self, value: ["id": id], update: .modified)
        }

        return user
    }
```

**Comment by alexeyn-martynov** [comment] 2023-06-26 09:41
Hey @dianaafanador3 , thanks for the advice! I'm totally gonna give it a shot. So, just to recap, my plan is to update Realm to the newest version and rewrite the saving part using the block method. It might take a while for me to gather the updated crash statistics though. Thanks a bunch for your help, and sorry for the delayed response!

**Comment by alexeyn-martynov** [comment] 2023-07-31 15:23
Hi! I'm not experiencing any more crashes after implementing the changes recommended in the comment above (https://github.com/realm/realm-swift/issues/8235#issuecomment-1569934657). My code (https://github.com/realm/realm-swift/issues/8235#issuecomment-1563421289) may leave the transaction in an opened state if the logic for 'Updating UserProfile properties' throws an exception. I suggest closing this ticket since it turned out to be an issue in my code. Thanks for your help!

**Comment by dianaafanador3** [comment] 2023-07-31 15:24
@alexeyn-martynov thanks for getting back to use, I'll close this.

**Closed** 2023-07-31 15:25 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Encryption:Off, Frequency:Sometimes, Repro:No
