### ISSUE TITLE
Writing data to Realm on background thread isn't being seen when returning to main thread, despite realm.refresh() being called

### ISSUE THREAD

**Issue by ragu-pdx** [realm/realm-swift#7625] opened 2022-01-21 06:32 UTC
### How frequently does the bug occur?

Sometimes

### Description

In the following code snippet, we are attempting to write data to Realm in a background thread, and once written, we call another method on the main thread  to retrieve more data.

```
   // Receive Data
    func peripheral(_ peripheral: PBPeripheral, readerOperationalData data: Data?, cartridgeId: String, startTime: Date) {
        DDLogDebug("\(peripheral.preferredName) received \(data == nil ? "no " : "")operational data for \(self.dataFilename(cartridgeId: cartridgeId, startTime: startTime)): \(data?.count ?? 0)")

        // Write data onto background thread backed by a RunLoop and blocks executed within an autoreleasepool
        let app = AppContext.shared.app
        DatabaseService.shared.writeAsync { [weak self, weak peripheral] in
            guard let `self` = self else { return }
            guard let realm = app.persistentRealm else { DDLogDebug("Persistent realm not accessible"); return }
            guard let object = realm.objects(ReaderTestResultObject.self).filter("\(#keyPath(ReaderTestResultObject.cartridgeId)) == %@ AND \(#keyPath(ReaderTestResultObject.startTime)) == %@", cartridgeId, startTime).first else {
                DDLogError("No test results object exists for \(self.dataFilename(cartridgeId: cartridgeId, startTime: startTime)). Ignoring operational data...")
                return
            }
            defer {
                // Check next ops data file to download
                DispatchQueue.main.async { [weak self, weak peripheral] in
                    guard let peripheral = peripheral else { return }
                    self?.transferNextFileIfAvailable(for: peripheral)
                }
            }

            // Update database object
            do {

*** UPDATES OBJECT ***
                try realm.write {
                    object.operationalDataState = opsDataState  // Value either -1 or 1
                    object.modifiedDate = Date()

                    realm.add(object, update: .modified)
                    DDLogDebug("Wrote opsDataState \(opsDataState.rawValue) for \(self.dataFilename(cartridgeId: cartridgeId, startTime: startTime)) @ \(object.modifiedDate.timeIntervalSince1970)")
                }
            } catch {
                DDLogError("Error writing updated result with ops data to persistent realm: \(error)")
            }
        }
    }

// Request New External Data
    func transferNextFileIfAvailable(for peripheral: PBPeripheral) {
        defer { self.uploadNextFileIfAvailable() }

        let app = AppContext.shared.app
        guard let readerSerialNumber = peripheral.deviceInformation?.serialNumber else { return }
        guard let realm = app.persistentRealm else { DDLogDebug("Persistent realm not accessible"); return }
        realm.refresh()

*** SHOULD READ UPDATED OBJECT ***
        guard let object = realm.objects(ReaderTestResultObject.self).filter("\(#keyPath(ReaderTestResultObject.serialNumber)) == %@ AND \(#keyPath(ReaderTestResultObject.operationalDataState)) == %d", readerSerialNumber, ReaderTestResultObject.OperationalDataState.unknown.rawValue).sorted(by: { $0.startTime < $1.startTime }).first else {
            return
        }

        DDLogDebug("(\(peripheral.preferredName)) Read opsDataState \(object.operationalDataState.rawValue) for \(self.dataFilename(cartridgeId: object.cartridgeId, startTime: object.startTime)) @ \(object.modifiedDate.timeIntervalSince1970)")
        DDLogDebug("\(peripheral.preferredName) requesting operational data for \(self.dataFilename(cartridgeId: object.cartridgeId, startTime: object.startTime))")
        peripheral.requestOperationalData(withCartridgeId: object.cartridgeId, date: object.startTime)
    }

```

The basic idea is that we have a bunch of Realm objects `ReaderTestResultObject` that represent external files we are retrieving. These objects start with an `opsDataState` of `0`. Once the file is pulled over, or not pulled over, we change `opsDataState` to `-1` or `1`, and then try to pull the next file. The process of figuring out what file to transfer is a Realm query to find the first object that still has a value of 0.

Most of the time, this code executes perfectly fine and doesn't pose any problems. The logic is sound for most users all the time.

However, on certain instances:

1. We query for the first object that has an `opsDataState` = 0
2. We attempt to retrieve the file, which may succeed or not.
3. On a background thread, we get the same object and update it's state to -1 or 1 (depending on whether we pulled data or not, and add an updated timestamp when the change occurred.
4. No error logs are printed, and the happy path of logs is always printed. The last log confirms the updated `opsDataState` in the write block.
5. We call the function to retrieve the next file on a DispatchQueue.async.main, which should cycle back to step 1
6. We expect that since we updated the opsDataState and time, that object should no longer be returned by the readQuery
7. The updated object isn't seen by the readQuery, and so keeps returning the same object to retrieve data on, and the cycle never stops.
8. We attempted to add a manual `realm.refresh()` call prior to searching for the next object to pull data for, but this failed to address the issue on the iOS devices experiencing the issue.

This is not dependent on Realm version, and we are always on the latest Realm version via Cocoapods. This issue was just seen today, so know that this is occurring on the latest Realm.

### Stacktrace & log output

Here is an example where we are attempting to pull a file for the given file name, the file wasn't found so we update the object to have an opsDataState of -1, but then on subsequent read to look for the first object that has an opsDataState value of 0, the same object is returned. We printed out the modifiedData timestamp of the object, and you can see that the date value never changes, even though on every write, it is being updated to the most current date of the system.

You should note that in the code snippet above, we log any and all potential errors that could happen at any given line, and the below, you will see an absence of any errors. All calls are successful in executing, whether it be getting the realm, writing data to realm, etc. However, the written data on the background thread is never seen on the main thread where it needs to be accessed, despite an explicit call to `realm.refresh()`.

```shell

2022-01-21 15:30:22.933 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:22.934 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739422.934417
2022-01-21 15:30:22.956 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:22.956 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:22.956 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.114 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:23.114 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:23.116 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739423.115747
2022-01-21 15:30:23.136 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:23.136 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.136 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.294 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:23.294 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:23.296 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739423.296088
2022-01-21 15:30:23.315 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:23.315 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.315 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.474 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:23.474 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:23.476 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739423.4757838
2022-01-21 15:30:23.496 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:23.496 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.497 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.651 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:23.651 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:23.653 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739423.6527162
2022-01-21 15:30:23.673 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:23.673 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.673 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.834 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:23.834 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:23.836 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739423.836217
2022-01-21 15:30:23.857 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:23.857 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:23.857 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.014 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.014 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.016 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.0158339
2022-01-21 15:30:24.038 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.038 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.038 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.194 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.195 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.196 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.196289
2022-01-21 15:30:24.218 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.218 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.218 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.370 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.371 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.372 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.372291
2022-01-21 15:30:24.392 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.392 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.392 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.554 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.554 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.555 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.555418
2022-01-21 15:30:24.577 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.577 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.577 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.734 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.734 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.736 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.735952
2022-01-21 15:30:24.736 [D] (SettingsCoordinator:163) Settings - selected reportIssue
2022-01-21 15:30:24.806 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.806 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.806 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.913 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:24.913 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:24.914 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739424.914372
2022-01-21 15:30:24.923 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:24.923 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:24.923 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:25.091 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-21 15:30:25.091 [D] (OperationalDataProcess:152) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-21 15:30:25.093 [D] (OperationalDataProcess:198) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1642739425.0929909
2022-01-21 15:30:25.113 [D] (OperationalDataProcess:82) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449
2022-01-21 15:30:25.113 [D] (OperationalDataProcess:83) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:25.113 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-21 15:30:25.274 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
```
```


### Can you reproduce the bug?

Not yet

### Reproduction Steps

_No response_

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS / iPadOS 15.2

### Build environment

Xcode version: 13.2.1
Dependency manager and version: Cocoapods 1.11.2

**Comment by leemaguire** [comment] 2022-01-21 09:39
Hi @ragu-pdx. Could you show us the code for `DatabaseService.shared.writeAsync` and how you are using the RunLoop?

**Comment by ragu-pdx** [comment] 2022-01-21 11:22
@leemaguire This is the code for the runloop threads. There is a single write thread launched at the beginning the application that lasts for the lifetime of the application. DatabaseService.shared.writeAsync {} just pipes the block to the perform function here. As mentioned, the code above works the majority of the time, but there are definitely issues getting the Realm to update on the main thread when written to on this RunLoopThread for a non-trivial amount of users.

```
class RunLoopThread: Thread {

    override init() {
        super.init()

        self.mcs_notificationController.addObserver(UIApplication.willTerminateNotification, sender: nil, queue: OperationQueue.main) { [weak self] (_) in
            self?.stop()
        }
    }

    deinit {
        DDLogDebug("[Thread] \(self.name ?? "Thread") deallocated")
    }

    override func main() {
        autoreleasepool {
            DDLogDebug("[Thread] \(self.name ?? "Thread") started")

            let runLoop = RunLoop.current
            runLoop.add(Port(), forMode: RunLoop.Mode.default)

            while !self.isCancelled {
                _ = autoreleasepool {
                    //  DDLogDebug("[Thread] Started Run Loop")
                    runLoop.run(mode: RunLoop.Mode.default, before: Date.distantFuture)
                    //  DDLogDebug("[Thread] Finished Run Loop")
                }
            }

            DDLogDebug("[Thread] \(self.name ?? "Thread") cancelled")
            Thread.exit()
        }
    }

    func perform(sync: Bool = false, _ block: @escaping () -> Swift.Void) {
        guard self.isExecuting else {
            if !self.isCancelled {
                DDLogVerbose("[Thread] \(self.name ?? String(describing: self)) hasn't started up yet. Starting soon...")
                if sync {
                    Thread.sleep(forTimeInterval: 0.002)
                    self.perform(sync: sync, block)
                } else {
                    DispatchQueue.global().asyncAfter(deadline: .now() + 0.002) { [weak self] in
                        guard let `self` = self else { return }
                        self.perform(sync: sync, block)
                    }
                }
            } else {
                DDLogError("[Thread] \(self.name ?? String(describing: self)) has already been cancelled!")
            }
            return
        }

        self.perform(#selector(RunLoopThread.execute), on: self, with: BlockWrapper(block), waitUntilDone: sync)
    }

    @objc fileprivate func execute(_ object: BlockWrapper) {
        let activity = ProcessInfo.processInfo.beginActivity(options: [.suddenTerminationDisabled, .automaticTerminationDisabled],
                                                             reason: "[Thread] \(self.name ?? "Thread") Doing Work")
        object.block()
        ProcessInfo.processInfo.endActivity(activity)
    }

    func stop() {
        self.perform(sync: true) {
            self.cancel()
        }
    }
}

private class BlockWrapper: NSObject {
    let block: () -> Void

    init(_ block: @escaping () -> Void) {
        self.block = block

        super.init()
    }
}
```

**Comment by ragu-pdx** [comment] 2022-01-21 11:25
We have been burned too many times in the past by the queue dynamics on Realms that we prefer to stick with a single persistent thread dedicated to Realm writes in the background. It's never been an issue in the past, so I'm not looking to change that code as it is very well ingrained into the codebase.

I just need to understand what it takes to get the writes taken on the background thread to update to the main thread within a single DispatchQueue.main.async call from the background thread back to the main thread. I thought this is what refresh() was supposed to do, but it isn't happening in this small subset of cases.

**Comment by leemaguire** [comment] 2022-01-21 12:39
@ragu-pdx you should not call `realm.refresh()` from the main thread, move it to be called after your write block (our docs also mention this). I would recommend revisiting the use of a serial queue too. Concurrent programming can have a lot of gotchas and [Apple does recommend queues over threads](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ConcurrencyandApplicationDesign/ConcurrencyandApplicationDesign.html#//apple_ref/doc/uid/TP40008091-CH100-SW1).

**Comment by leemaguire** [comment] 2022-01-21 15:10
@ragu-pdx We are currently implementing a way to perform write transactions asynchronously. This should help your use case once released https://github.com/realm/realm-swift/pull/7576

**Comment by RVijay007** [comment] 2022-01-21 16:18
There are many reasons we cannot rely on queues solely, not withstanding queue vs explicit Thread behavior in background app states. Our use case with our application needs to be as reliable in the background context as in the foreground. As mentioned several times, this logic is working the majority of the time. 95% of users see this logic between finding the next file to download on the main thread, write the file on a background thread and update the Realm on the background thread ... working all the time. But then some users, and it's unclear what aspect of the whole system is breaking down. Printing the size of the realm only returns 2MB, so doesn't seem to be related to Realm file system size.

Regardless, sounds like you are saying that the refresh needs to be called in the thread context with the thread's version of Realm. Many [SO articles](https://stackoverflow.com/questions/45809717/after-writing-to-a-realm-in-background-thread-the-main-thread-doesnt-see-updat) mention calling it at the start of a context that would be executed in the main thread. If all write transactions block any other write transaction, why doesn't a refresh from the main context work to update the main thread Realm to the latest state?

Reference: https://github.com/realm/realm-swift/issues/5487
"Calling refresh() immediately after a write transaction is unlikely to do anything as the Realm was already at the most recent version when the write transaction was committed, and it's incredibly unlikely that another thread was able to commit a write transaction in the mean time."

**Comment by ragu-pdx** [comment] 2022-01-21 16:41
@leemaguire There are many reasons we cannot rely on queues solely, notwithstanding queue vs explicit Thread behavior in background app states. Our use case with our application needs to be as reliable in the background context as in the foreground. We actually modeled this after Realm's own posts, i.e. [Background Worker](https://academy.realm.io/posts/realm-notifications-on-background-threads-with-swift/). As mentioned several times, this logic is working the majority of the time. 95% of users see this logic between finding the next file to download on the main thread, write the file on a background thread and update the Realm on the background thread ... working all the time. If is was a code problem with our RunLoopThread, our app would be broken in so many other way as well, including receiving Realm notifications throughout the app, which hasn't been the case.  

However some users, and it's unclear what aspect of the whole system is breaking down. Printing the size of the realm only returns 2MB, so doesn't seem to be related to Realm file system size.

The specific abstract case that we see possibly creating the problem is 

```
writeDatainBackgroundThread {
        Access realm and specific object
        Write data in a realm.write transaction
// Your advice: realm.refresh() called here?
        DispatchQueue.main.async { self.doWorkOnMain() }
}

doWorkOnMain() {
      Access Realm on main thread
      Access realm object by searching for it
// To realm.refresh() or not???
      Read realm object properties that should have been updated on write thread
}
```

When we do this limited case, this doesn't always seem to update the information written on the background thread by the time we hit the main thread function. 

Regardless, sounds like you are saying that the refresh needs to be called in the thread context with the thread's version of Realm. Many [SO articles](https://stackoverflow.com/questions/45809717/after-writing-to-a-realm-in-background-thread-the-main-thread-doesnt-see-updat) mention calling it at the start of a context that would be executed in the main thread. If all write transactions block any other write transaction, why doesn't a refresh from the main context work to update the main thread Realm to the latest state?

Reference: https://github.com/realm/realm-swift/issues/5487
"Calling refresh() immediately after a write transaction is unlikely to do anything as the Realm was already at the most recent version when the write transaction was committed, and it's incredibly unlikely that another thread was able to commit a write transaction in the mean time."

**Comment by tgoyne** [comment] 2022-01-21 17:21
The two scenarios where `refresh()` will simply return false and do nothing despite there being newer versions available are if the Realm is frozen, or if the call to `refresh()` occurs within a callback for a change notification. If you're using frozen Realms at all, it's worth double-checking that there's no possible way that you could accidentally sometimes be using a frozen Realm at this point, although that seems pretty unlikely to me.

The explanation that the Realm isn't refreshing because it thinks it's in the middle of sending change notifications seems more likely to me. If you're ever calling `runLoop.run()` on the main thread then all of this code could plausibly be running inside a change callback. If you aren't, then it probably means that something prior to this resulted in the Realm's internal state becoming invalid making it think that it's currently calling change callbacks when it isn't?

**Comment by ragu-pdx** [comment] 2022-01-21 17:41
@tgoyne We are not, nor ever have, used frozen Realms. This is the only code block within our entire app that is calling `refresh()`, and actually for the longest time, we weren't even calling `refresh()`. We only added an explicit call to `refresh()` here because of this issue, thinking maybe there was some disconnect between writing on the background thread and seeing those changes on the main thread with a single `DispatchQueue.main.async()` call. However, because it isn't helping so far, I'm not sure whether the call is necessary or not?

**Comment by tgoyne** [comment] 2022-01-21 17:51
Without the call to `refresh()` you do have a race condition, but it's fairly benign. If the dispatch_async() to the main thread beats out the autorefresh, it'd result in you processing an object twice (but normally not more than twice).

**Comment by ragu-pdx** [comment] 2022-01-21 17:59
@tgoyne So given that may be the case in these unique user instances, if we are calling refresh(), should we be calling it right after the write transaction, with the refresh executed in the background write thread? Or does it need to be called on the main thread? See pseudo in my comment a few posts ago to see the 2 locations I'm debating putting the `refresh()` block.

In either case, even if it is worse performance-wise on the main thread, it should still do the job of bringing the main thread Realm instance up-to-date. However calling it on the main thread did not address this ... the object's data was still 'stale' and old, and I'm unsure why that is?

**Comment by ragu-pdx** [comment] 2022-01-24 04:03
@tgoyne We moved the `realm.refresh()` line immediately after the write block rather than prior to the read executed on the main thread. This failed to fix the issue on our 1 iOS device that is demonstrating the issue. Any other ideas?

> Reference

**Comment by ragu-pdx** [comment] 2022-01-25 03:38
As an update, we pushed a build to print out whether the Realms on either the write thread or main thread (read) were frozen. As expected, neither realms are frozen.

```
2022-01-25 14:16:23.512 [D] (PBObjectTransferService:312) (Proof Lab 0117) Resetting OTS Service...
2022-01-25 14:16:23.512 [D] (OperationalDataProcess:150) Proof Lab 0117 received no operational data for 2021-12-17T01-07-22Z_C9991234567.tgz: 0
2022-01-25 14:16:23.549 [D] (OperationalDataProcess:199) Wrote opsDataState -1 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1643080583.5237179. Frozen? false
2022-01-25 14:16:23.557 [D] (OperationalDataProcess:81) (Proof Lab 0117) Read opsDataState 0 for 2021-12-17T01-07-22Z_C9991234567.tgz @ 1639703534.536449. Frozen? false
2022-01-25 14:16:23.557 [D] (OperationalDataProcess:82) Proof Lab 0117 requesting operational data for 2021-12-17T01-07-22Z_C9991234567.tgz
2022-01-25 14:16:23.558 [D] (PBObjectTransferService:273) (Proof Lab 0117) Attempting to download operational data file: results/2021-12-17T01-07-22Z_C9991234567.tgz
```

So still no idea why the writes on the thread are not being seen on the read. This issue is persisting across app installations, so through full process shutdowns and restarts.

**Comment by tgoyne** [comment] 2022-01-26 01:30
Does this happen if you downgrade to Realm 10.21.0? The changes between 10.21.0 and 10.21.1 include a lot of refactoring to the relevant code (to support the upcoming async writes feature), and while I don't specifically see any changes that obviously would cause this problem, the fact that you only recently started seeing this and the code was touched recently makes me suspect we introduced a bug there.

**Comment by ragu-pdx** [comment] 2022-01-29 23:35
@tgoyne We are still seeing the issue on 10.21.0

**Comment by tgoyne** [comment] 2022-02-04 16:59
I don't really have ideas for what could be causing this. The really brute-force way to ensure that a Realm is at the latest version is to begin and then cancel a write transaction on the main thread. It's not a good solution as it'll block the main thread while a write on a background thread is happening, but if even that doesn't work then it indicates that the problem is that the background write isn't actually getting committed.

**Comment by leemaguire** [comment] 2022-02-21 12:02
@ragu-pdx were you able to try the above suggestion of performing a write transaction on the main thread and cancelling it? If so did it yield a plausible workaround?

**Comment by pavel-ship-it** [comment] 2022-05-31 09:13
Hi @ragu-pdx, have you had a chance to try the workaround with begin/cancel the transaction?

**Comment by huforrest** [comment] 2022-07-13 08:41
I meet the same issue and have no idea what's going wrong.

**Comment by huforrest** [comment] 2022-07-13 08:46
> @ragu-pdx were you able to try the above suggestion of performing a write transaction on the main thread and cancelling it? If so did it yield a plausible workaround?

I have the same issue on iOS15.5. It works fine on previous iOS versions. Can you guys help to solve the problem?

**Comment by huforrest** [comment] 2022-07-14 02:41
> I don't really have ideas for what could be causing this. The really brute-force way to ensure that a Realm is at the latest version is to begin and then cancel a write transaction on the main thread. It's not a good solution as it'll block the main thread while a write on a background thread is happening, but if even that doesn't work then it indicates that the problem is that the background write isn't actually getting committed.

I have met the same issue on iOS15.5. It works fine on previous iOS versions. Have you guys ever met this problem? Can you guys help to solve the problem?

**Comment by tgoyne** [comment] 2022-08-29 18:00
I stumbled across what's causing this. It turns out that there's a scenario where `refresh()` was intentionally not advancing to the latest version, but in a way that's not actually documented and was just a bad idea.

**Closed** 2022-09-10 00:20 UTC
Labels: T-Bug, O-Community
