### ISSUE TITLE
Set ignored mutable properties in initWithValue:

### ISSUE THREAD

**Issue by Kalzem** [realm/realm-swift#3495] opened 2016-04-28 10:35 UTC
## Goals

I want to set an ignored property using this type of constructor
`let duck = Duck(value: [ "animal": [ "age": 3 ], "name": "Gustav" ])`
## Expected Results

The ignored property is correctly set
## Actual Results

The constructor doesn't care about my ignored property
## Steps to Reproduce
1. Define a model
2. Define an ignored property either optional or not
3. Create an object using the constructor with `value`
4. The ignored property is not set correctly
## Code Sample

```
class User: Object {
    dynamic var id: String = ""
    dynamic var firstName: String? = nil
    dynamic var lastName: String? = nil

    //Ignored property
    dynamic var isPending: Bool = false

    override static func primaryKey() -> String? {
        return "id"
    }

    override static func ignoredProperties() -> [String] {
        return ["isPending"]
    }
}
```

And in the controller, I do this:

```
let user = User(value: ["id": "123", "firstName": "FIRST", "lastLame": "LAST", "isPending": true])
print(user.isPending) // Should show TRUE, but shows FALSE
```
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.98.latest

Xcode version: 7.3

iOS/OSX version: 9.3

Dependency manager + version: Carthage latest of April 2016

**Comment by jpsim** [comment] 2016-04-28 10:42
The `initWithValue:` initializer only considers keys for persisted properties at the moment. This is a feature request, so I've marked it as such.

**Comment by BabyAzerty** [comment] 2016-04-28 10:53
"It's not a bug, it's a feature" haha 😆 
It would be great to mention it in the guide & API.

**Closed** 2022-03-28 17:10 UTC
Labels: T-Enhancement, O-Community, Pipeline-Idea-Backlog
