### ISSUE TITLE
The result of sort with multiple fields will not be consistent

### ISSUE THREAD

**Issue by ananfang** [realm/realm-swift#7188] opened 2021-03-23 15:26 UTC
## Goals

Sort documents by multiple field when using MongoDB collection find or aggregate.
e.g. {$sort: {createdAt: -1, username: 1}}

## Expected Results

First sort by createdAt in descending order and then sort by username in ascending order.

## Actual Results

Since Dictionary in Swift or NSDictionary in Objective-C is unordered collection, the order of {$sort: {createdAt: -1, username: 1}} is uncertain, it could not make sure the consistency of sort order.

For example, using FindOptions for finding document

```
let options = FindOptions(limit: 20, projection: nil, sort: ["createdAt": -1, "username": 1])
collection.find(filter: ["favorite": "MongoDB Realm"], options: options)
```

This result will be not consistent, because the result could be sorted by createdAt than username or by username than createdAt.

## Version of Realm and Tooling

Realm framework version: 10.7.2

Xcode version: 12.4

iOS/OSX version: 14.4

Dependency manager + version: Swift Package Manager

**Comment by dianaafanador3** [comment] 2021-03-23 15:29
HI @ananfang can you give us more info about this?, maybe an example of what you want?

**Comment by ananfang** [comment] 2021-03-23 15:37
> HI @ananfang can you give us more info about this?, maybe an example of what you want?

@dianaafanador3 Sorry for mistake, I've updated more information.

**Comment by dianaafanador3** [comment] 2021-03-23 15:53
Hi @ananfang thanks for the update, I'll check this and will get back to you.

**Comment by ananfang** [comment] 2021-03-24 04:19
I've tested again, and here is the result

```
let findOptions = FindOptions(20, nil, [
            "username": 1,
            "name": -1,
            "brief": 1,
            "updatedAt": -1
        ])
someCollection.find(filter: [:], options: findOptions)
```

I ran this query three times, and the sort order was different each time:
1st: {username: 1, name: -1, brief: 1, updatedAt: -1}
2nd: {updatedAt: -1, brief: 1, name: -1, username: 1}
3rd: {brief: 1, username: 1, updatedAt: -1, name: -1}

**Comment by dianaafanador3** [comment] 2021-03-24 10:59
Hi @ananfang as you can see if you query the collection the resulted `[Document]` contains an array of `Dictionary<String, AnyBSON?>`, dictionaries are not intended to be ordered, so we cannot guarantee the order of the resulted dictionary.

If you want control over which properties of the collection to return you can use `projections`
https://docs.mongodb.com/manual/reference/method/db.collection.find/#method-find-projection,
or if you want to order your documents in the result set, you can use `sort`.

**Comment by ananfang** [comment] 2021-03-24 12:15
> or if you want to order your documents in the result set, you can use `sort`.

Yes, I want to order the documents in the result set. And if I use mutiple sort options (e.g. {fieldA: 1, fieldB: -1, fieldC: 1}), eventually it will not guarantee the order of sort options, since Dictionary in Swift is unordered collection. 

But the order of sort options is important, different order will result different documents in return. I'vd tested, and found the order is not consistent based the logs from MongoDB Realm app. 

Please review again.

**Comment by ananfang** [comment] 2021-03-24 12:24
@dianaafanador3 
I think this issue should be reopen (I just left the reason above), but I can't. 

Could you help me to reopen this issue?

**Comment by dianaafanador3** [comment] 2021-03-24 14:30
Hi @ananfang so sorry, i misunderstood your question.
In case of comparing values of different BSON types, mongodb uses the following comparison order, from lowest to highest
```
MinKey (internal type)
Null
Numbers (ints, longs, doubles, decimals)
Symbol, String
Object
Array
BinData
ObjectId
Boolean
Date
Timestamp
Regular Expression
MaxKey (internal type)
```
You can find the complete documentation here.
https://docs.mongodb.com/manual/reference/method/cursor.sort/#sort-asc-desc

**Comment by ananfang** [comment] 2021-03-25 09:54
@dianaafanador3 The sort order I mentioned is **NOT** BSON type sort for the same field.
> Hi @ananfang so sorry, i misunderstood your question.
> In case of comparing values of different BSON types, mongodb uses the following comparison order, from lowest to highest
> You can find the complete documentation here.
> https://docs.mongodb.com/manual/reference/method/cursor.sort/#sort-asc-desc

Let me describe more detail with example data and sample code.

First, if we have the following data:
```
[
    {"username": "Andy", "name": "The 2nd Knight", "updatedAt": "2019-12-31T16:00:00.000+00:00", "brief": "Green", "followerCount": 15},
    {"username": "Bill", "name": "The 3rd Knight", "updatedAt": "2020-01-12T05:46:40.000+00:00", "brief": "Blue", "followerCount": 213},
    {"username": "Carl", "name": "The 4th Knight", "updatedAt": "2020-01-23T19:33:20.000+00:00", "brief": "Red", "followerCount": 49},
    {"username": "Danny", "name": "The 5th Knight", "updatedAt": "2019-12-08T12:26:40.000+00:00", "brief": "Orange", "followerCount": 30},
    {"username": "Fred", "name": "The 1st Knight", "updatedAt": "2019-12-20T02:13:20.000+00:00", "brief": "Yellow", "followerCount": 38}
]
```

And then using the MongoDB Realm iOS SDK directly access to MongoDB.
```
let findOptions = FindOptions(20, nil, ["username": 1, "name": -1, "updatedAt": -1, "brief": 1, "followerCount": 1])
collection.find(filter: [:], options: findOptions)
```

And you'll find that every time you execute the "find" query, the documents in return will be in different order. Because the following order is important and should be consistent:
`["username": 1, "name": -1, "updatedAt": -1, "brief": 1, "followerCount": 1]`

Since Dictionary in Swift is unordered collection, this order is not guaranteed to be the same every time. Eventually it will cause the query result will be in the same order.

I've created a sample code for demo, please refer to this repository:
[ananfang/mongodb-realm-sorting-issue](https://github.com/ananfang/mongodb-realm-sorting-issue)
(It's a private repository, I've added you as a collaborator)

**Comment by dianaafanador3** [comment] 2021-03-25 09:56
Hi @ananfang thanks for the invite to the repo, I'll take a llok at it as soon as possible.

**Comment by ananfang** [comment] 2021-04-19 15:53
@dianaafanador3 Any update for this issue?

**Comment by dianaafanador3** [comment] 2021-04-19 16:00
HI @ananfang, actually i reviewed this today and checked that everything is ok in our side (Cocoa), conclusion, unordered results are coming from the server. 
I asked in our internal channels for an answer on mongo side, I'll let you know when we get an answer as soon as possible.

**Comment by ananfang** [comment] 2021-04-19 16:36
> HI @ananfang, actually i reviewed this today and checked that everything is ok in our side (Cocoa), conclusion, unordered results are coming from the server.

@dianaafanador3 Since the Dictionary in Swift is unordered and we put a sort options in the Dictionary, it'll cause the inconsistent result. Thus I think this issue definitely happened in the client SDK, not server side. Please kindly review it again.

**Comment by dianaafanador3** [comment] 2021-04-19 17:01
@ananfang I checked that your result set was returning different order each time, (not the properties within the document dictionary, this will be unordered since dictionary in swift is unordered). The result that is been returned by the server has a different order each time we call the find function, and should be the same, this is not happening for example in the case of using just a sorting argument like `["username": 1]`.

**Comment by ananfang** [comment] 2021-04-20 04:46
> @ananfang I checked that your result set was returning different order each time, (not the properties within the document dictionary, this will be unordered since dictionary in swift is unordered). The result that is been returned by the server has a different order each time we call the find function, and should be the same, this is not happening for example in the case of using just a sorting argument like `["username": 1]`.

@dianaafanador3 

Yes. The reason why server returned inconsistent results is that every time client SDK iterates sort options in Dictionary to call API, and Dictionary is unordered, each iteration will be different. Thus the sort options of the real API call from client is different each time, then the server will return inconsistent results.

I suggest that maybe we could use array to wrap the sort options in client SDK, since it's ordered.

**Comment by dianaafanador3** [comment] 2021-04-22 07:32
HI @ananfang, you are right about this issue in our API (I'm sorry it took me so much to see it) and we are discussing solutions for this. We'll try to fit a fix for this in future releases. 
For now I'll recommend to do the sorting by just one property as using more than one could cause an unordered set.

**Comment by ananfang** [comment] 2022-03-18 23:22
It's almost 1 year, any update for this issue?

**Comment by dianaafanador3** [comment] 2022-03-24 09:32
Hi @ananfang, unfortunately this will be a breaking change in our API, we will need to change the API to allow something that is not a Document `Dictionary<String, AnyBSON?>` (for example SortDescriptor could work here), which is only allowed on major versions. Also, this will make the API less flexible in case there is a change on Mongo's side. We'll keep discussing this for a future major release.

**Comment by davidkessler-ch** [comment] 2023-01-18 08:57
@dianaafanador3 Any update on when a major release including this could be happening? Sorting in queries with multiple keys is a quite fundamental requirement that is probably needed by lots of people. Also there is not really a workaround for this, which is why we would have to consider switching to some other provider if this is not fixed..

P.S. I would also suggest to make a note in the SwiftSDK documentation if it is not fixed soon, since it can lead to "unexpected behaviour" when simply following the docs the way they are now..

**Comment by dianaafanador3** [comment] 2023-01-18 09:20
Hi @davidkessler-ch this is tagged for our next major release, which we don't have a release date for now. If this is something critical for you, I'll put it for discussion with the team and see if we can work something out.

**Comment by davidkessler-ch** [comment] 2023-01-18 09:34
Thanks for the quick reply. Yes, that would be greatly appreciated!

**Comment by dianaafanador3** [comment] 2023-05-02 07:53
Fixed by this PR https://github.com/realm/realm-swift/pull/8181

**Closed by dianaafanador3** 2023-05-02 07:53 UTC
Labels: O-Community
