### ISSUE TITLE
No properties are defined for 'Model'

### ISSUE THREAD

**Issue by igormagurean** [realm/realm-swift#8074] opened 2022-12-19 17:22 UTC
### How frequently does the bug occur?

All the time

### Description

We have migrated from objc Realm to RealmSwift `~>10.0`. The crash happens on firebase distribution(test) and TestFlight builds and is _**NOT**_ happening in Xcode or simulator, or real device connected to xcode.

Any ideas what is going on here?

```
//Somewhere in migration class
migration.enumerateObjects(ofType: RealmChannel.className()) { oldObject, newObject in
            if let id  = oldObject?["_id"] as? String {
                newObject!["id"] = id
            }
        }

import RealmSwift

class RealmChannel: Object {
    @Persisted(primaryKey: true) var id: String = ""
    @Persisted var name: String?
    @Persisted var followers: Int = 0
    @Persisted var countryFollowers: Int = 0
    @Persisted var badge: String?
    @Persisted var lastAccessTime: Int64 = Int64(Date().timeIntervalSince1970 * 1000.0)
    @Persisted var unread = false
    @Persisted var canDeletePost = false
    @Persisted var canBanChannelUser = false
    @Persisted var emoticon: String?
    @Persisted var descriptionKey: String?
    @Persisted var lastPostedTimestamp: Int64 = 0
    @Persisted var channelFeatures: String?
    
    convenience init(id: String) {
        self.init()
        self.id = id
    }
}
```

### Stacktrace & log output

```shell
*** Terminating app due to uncaught exception 'RLMException', reason: 'No properties are defined for 'RealmChannel'. Did you remember to mark them with '@objc' in your model?'
*** First throw call stack:
(0x1a8dc1dc0 0x1bd91e7a8 0x101e82344 0x101f57530 0x101f57be0 0x1a8d26104 0x1a8c9a888 0x101f57a70 0x101f4ab50 0x1028a1228 0x1028a16a4 0x100a89c40 0x100a89ba0 0x1a89ae81c 0x1a89b00b4 0x1accde97c 0x100b5db2c 0x100a3dad8 0x100a3de14 0x100c60264 0x100c6072c 0x1ab7af980 0x1ab7b1414 0x1ab7b7560 0x1aae0b1ac 0x1ab374458 0x1aae0bd44 0x1aae0b804 0x1aae0bb54 0x1aae0b390 0x1aae138d4 0x1ab281e84 0x1ab38d268 0x1aae135cc 0x1aac3b4b4 0x1aac39e34 0x1aac3b0dc 0x1ab7b5700 0x1ab2ab4e4 0x1b83e65d8 0x1b8411d44 0x1b83f56a4 0x1b8411a0c 0x1a89ae81c 0x1a89b230c 0x1b8439fa0 0x1b8439c30 0x1b843a184 0x1a8d3c07c 0x1a8d3bf78 0x1a8d3b27c 0x1a8d3525c 0x1a8d349f4 0x1c040a734 0x1ab7b375c 0x1ab7b8fcc 0x1007ee040 0x1a89f0cf8)
```

### Can you reproduce the bug?

Yes, always

### Version

RealmSwift `~>10.0`

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15

### Build environment

Xcode version: 14
Dependency manager and version: 1.11.3

**Comment by RRR008** [comment] 2023-02-03 12:34
Hi @igormagurean ,
I am also facing same issue , did you mange to resolve this issue. Please let me know it's taking ages to find a workout.
I am using Xcode 14.2 and MacOS ventura.
Thank You

**Comment by igormagurean** [comment] 2023-02-13 10:27
Not yet.

> Hi @igormagurean , I am also facing same issue , did you mange to resolve this issue. Please let me know it's taking ages to find a workout. I am using Xcode 14.2 and MacOS ventura. Thank You

Not yet.

**Comment by michalcichon** [comment] 2023-03-04 20:03
Hey. 

We identified the issue, the problem was that we used `SWIFT_REFLECTION_METADATA_LEVEL = none;` Swift compiler flag in our RELEASE configuration and `SWIFT_REFLECTION_METADATA_LEVEL = all;` in DEBUG. We couldn't reproduce the issue in the DEBUG mode obviously because the reflection worked fine, and it seems that RealmSwift utilize heavily the reflection features of Swift. That's why it crashed on our TestFlight and Firebase builds.

I think we can close this issue ticket. (@igormagurean can you confirm?). But please make sure you reflect this in your installation documentation. It took us a while to figure out what can be wrong with our persistence layer.

**Comment by igormagurean** [comment] 2023-03-06 09:43
`None:` No reflection metadata is emitted into the binary. Accuracy of detecting memory issues involving Swift types in the Memory Graph Debugger will be degraded and reflection in Swift code may not be able to discover children of types, such as properties and enum cases.

**Closed** 2023-03-06 09:44 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Frequency:Always, Repro:Always, Encryption:On
