### ISSUE TITLE
Expect realm update notify is modification, but get insertion instead

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-swift#7184] opened 2021-03-22 01:20 UTC
So imagine we have a Shelf Object type and Item Object:
```swift
    fileprivate let ShelfPrimaryKey = "shelfName"
    class Shelf: Object {
        @objc dynamic private var shelfName: String!
        private let rlmItems = List<Item>()
    
        private override init() {
            super.init()
        }
    
        private init(name: String) {
            super.init()
            shelfName = name
        }
    
        override static func primaryKey() -> String? {
            return ShelfPrimaryKey
        }
    }

    fileprivate let ItemPrimaryKey = "itemName"
    fileprivate let LinkingObjectsReverseKey = "rlmItems"
    class RealmItem: Object {
        @objc dynamic private var itemName: String!
        private let reversedShelves = LinkingObjects(fromType: RealmShelf.self, property: LinkingObjectsReverseKey)
    
        @objc dynamic internal var itemIdealShelf: RealmShelf?
        @objc dynamic internal var itemShelf: RealmShelf? { return reversedShelves.first }
        override static func primaryKey() -> String? {
            return ItemPrimaryKey
        }
    }
```
This is how I add them into Realm:
```swift
    func writeItem(itemName: String, shelfName: String) {
        writeQueue.async {
            autoreleasepool {
                do {
                    let realm = try Realm()
                    let item = RealmItem.getRealmItem(itemName, in: realm)
                    let targetShelf = RealmShelf.getRealmShelf(shelfName, in: realm)
                    try realm.write {
                        if let currentShelf = item.itemShelf {
                            if currentShelf != targetShelf {
                                currentShelf.removeItem(item)
                                targetShelf.add(item)
                            }
                        } else {
                            targetShelf.add(item)
                        }
                        realm.add(targetShelf, update: .modified)
                    }
                }
                catch {
                    logger.error("Failed to write Realm")
                }
            }
        }
    }
```
**Both shelf and item use its name as primary key**

The idea is if an item is updated its shelf, remove it from old shelf and add into the new one.
`getRealmShelf` and `getRealmItem` will fetch an existing one by the primary key, or create a new one if not exist. 

Then I have an UITableView to display item : shelf relation.

I have an observer using Realm API to update the table view, as suggested in [here][1]
```swift
    func addItemObserver() {
        token = rlmItems?.observe { [weak self] changes in
            if let tableView = self?.itemTableView {
                switch changes {
                case .initial(_):
                    logger.debug("realm get initial notifications, reloading table view...")
                    tableView.reloadData()
                case .update(_, let deletions, let insertions, let modifications):
                    logger.debug("realm get updates, updating tablew view...")
                    logger.debug("insertions \(insertions)")
                    logger.debug("modifications \(modifications)")
                    // Query results have changed, so apply them to the UITableView
                    tableView.performBatchUpdates({
                        // Always apply updates in the following order: deletions, insertions, then modifications.
                        // Handling insertions before deletions may result in unexpected behavior.
                        tableView.deleteRows(at: deletions.map({ IndexPath(row: $0, section: 0)}),
                                             with: .automatic)
                        tableView.insertRows(at: insertions.map({ IndexPath(row: $0, section: 0) }),
                                             with: .automatic)
                        tableView.reloadRows(at: modifications.map({ IndexPath(row: $0, section: 0) }),
                                             with: .automatic)
                    })
                case .error(let error):
                    logger.error("realm receives \(error)")
                }
            }
        }
    }
```
During test, I found that, the `modifications` is always empty, and it seems Realm treat all the write transactions as insertions, not modifications, so leading to the table view is always inserting rows and no reloadRows happens, hence it's not reflecting the latest state of item.

I want ask, is this something I did wrong, or this is expected behavior?

I know there is a quick around is to call `reloadData` all the time, but I wanted to have more fine-grained control here.

  [1]: https://docs.mongodb.com/realm/sdk/ios/examples/react-to-changes/

**Comment by liuxuan30** [comment] 2021-03-22 01:29
I also write a UT to make it simple:
```swift
    func testWriteNotify() {
        let e1 = XCTestExpectation()
        let e2 = XCTestExpectation()
        // generator: https://tools.knowledgewalls.com/jsontostring
        let jsonStr = "[{\"id\":\"bafe7b5b-fec9-433e-81f7-0610beeb9623\",\"price\":6046,\"item\":\"Pizza\",\"customer\":\"Kayn\",\"destination\":\"965 Giovanna Knoll, Dwainfurt, SC 91343\",\"state\":\"CREATED\",\"shelf\":\"NONE\",\"idealShelf\":\"FROZEN\",\"timestamp\":1616050043907}]"

        let json = getJson(jsonStr)

        var isModify = false
        let items = realm.objects(RealmItem.self)
        let token = items.observe { [weak self] changes in
            switch changes {
            case .initial(_):
                logger.debug("realm initial \(items.first)")
                e1.fulfill()
            case .update(_, let deletions, let insertions, let modifications):
                logger.debug("realm update delete: \(deletions), insert: \(insertions), modify: \(modifications)")
                isModify = modifications.count > 0
                e2.fulfill()
            default:
                break
            }
        }

        RealmOrderManager.sharedManager.write(json: json)

        // write(json: json) is in another serial queue
        // make sure write finished, or we will get the object in current thread too quick
        var barrier = XCTestExpectation()
        testQueue.asyncAfter(deadline: .now() + 2) {
            barrier.fulfill()
        }

        wait(for: [e1, barrier], timeout: UTTimeout)
        RealmOrderManager.sharedManager.writeItem(itemName: "Pizza", shelfName: "HOT")

        // writeItem() is in another serial queue
        // make sure write finished, or we will get the object in current thread too quick
        barrier = XCTestExpectation()
        testQueue.asyncAfter(deadline: .now() + 2) {
            barrier.fulfill()
        }
        wait(for: [e2, barrier], timeout: UTTimeout)
        XCTAssertEqual(items.first?.shelf.name, .hot)

        RealmOrderManager.sharedManager.writeItem(itemName: "Pizza", shelfName: "COLD")

        // writeItem() is in another serial queue
        // make sure write finished, or we will get the object in current thread too quick
        barrier = XCTestExpectation()
        testQueue.asyncAfter(deadline: .now() + 2) {
            barrier.fulfill()
        }
        wait(for: [barrier], timeout: UTTimeout)

        token.invalidate()

        XCTAssertEqual(items.first?.shelf.name, .cold)
        XCTAssertTrue(isModify)
    }
```
and it seems the  UT is unstable, seems Realm would combine the three writes into a single write, or twice, instead of a mofication.

sometimes the UT will fail at
>wait(for: [e2, barrier], timeout: UTTimeout)

saying e2 is not fulfilled, meaning only `initial` get called, and no `update` branch.

could I also ask how to improve the UT to test what I wanted?

**Comment by dianaafanador3** [comment] 2021-03-23 10:33
Hi @liuxuan30, I see you have two open similar issues, Im closing this one https://github.com/realm/realm-cocoa/issues/7185?, and i'll address both questions/issues here. I'll try to get to you as quickly as possible.

**Comment by liuxuan30** [comment] 2021-03-23 10:52
@dianaafanador3 this is kind of different issues, I'm ok if you close one, jus making sure you understand

**Comment by liuxuan30** [comment] 2021-03-23 10:53
this one is kind of not able to get modifications, #7185 is about not able to get "notification" at all, on LinkingObejcts

**Comment by dianaafanador3** [comment] 2021-03-23 10:56
Hi @liuxuan30 I'll address both question/issue here, given that is the same code

**Comment by dianaafanador3** [comment] 2021-03-23 11:38
Related to this issue https://github.com/realm/realm-cocoa/issues/7185

**Comment by liuxuan30** [comment] 2021-03-24 01:15
yeah the schema definition is the same, it's just that I ran into different issues. thank you

**Comment by pavel-ship-it** [comment] 2022-07-13 10:42
Hi @liuxuan30 
In that case you should not get a notification - It will be triggered in case of collection of object has some changes (Not the object in the collection) - it means the notification will be triggered if you add, remove or replace the object.

In the example above you could try to observe the state of the specific shelf:
```
                let shelfObservationToken = try! Realm().objects(RealmShelf.self).first!
.observe { changes in
                        print("SHELF \(changes)")
                }
```

Depending on the requirements you could try to observe the filtered collection or to observe the specific items.

I'm closing the issue as it's not a bug.

**Closed by pavel-ship-it** 2022-07-13 10:42 UTC
Labels: O-Community
