### ISSUE TITLE
@AutoOpen does not work offline

### ISSUE THREAD

**Issue by Jonovono** [realm/realm-swift#8420] opened 2023-11-13 23:10 UTC
### How frequently does the bug occur?

Always

### Description

I am unable to access my realm offline. I am not sure if the way I am doing is expeced, but from reading https://www.mongodb.com/developer/products/realm/realm-asyncopen-autoopen/ I should be able to just use AutoOpen and then it should work offline. I will show you my code and hopefully someone can point out if I am doing something wrong or if this is a bug. 

```
public struct App: View {
    @StateObject var errorHandler = ErrorHandler(app: AtlasClient.shared.app)

    public init() {}

    public var body: some View {

        ContentView(app: AtlasClient.shared.app)
            .environmentObject(errorHandler)
```

```
public class AtlasClient: ObservableObject {
    public static let shared = AtlasClient()

    public let app: App

    var token: NotificationToken?

    public var appId: String {
        return theRealmAppConfig.appId
    }

    public init() {
        self.app = App(
            id: theRealmAppConfig.appId
        )

        app.objectWillChange.sink { _ in
            if let user = self.app.currentUser {
                print("User is authenticated with user id: \(user.id)")
            } else {
                print("User is not authenticated")
            }
        }
    }

    public func createMongoUser(token: String) async throws -> User {
        let credentials = Credentials.jwt(token: token)
        let user = try await app.login(credentials: credentials)
        return user
    }
}
```

```
struct ContentView: View {
    @ObservedObject var app: RealmSwift.App
    @State private var hasTrackedAppLaunch = false
    @State var onboardData: OnboardData?
    @AppStorage("onboarded") var onboarded: Bool = false

    func onOnboarded(data: OnboardData) {
        onboardData = data
        onboarded = true
    }

    var body: some View {
        Group {
            if let user = app.currentUser, onboarded {
                let userId = try! ObjectId(string: user.id)

                let config = user.flexibleSyncConfiguration(clientResetMode: .recoverOrDiscardUnsyncedChanges(), initialSubscriptions: { subs in


                    if let foundSub = subs.first(named: Constants.Realm.getUser) {
                        foundSub.updateQuery(toType: Shopper.self) { shopper in
                            shopper._id == userId
                        }
                    } else {
                        subs.append(
                            QuerySubscription<Shopper>(name: Constants.Realm.getUser) { shopper in
                                shopper._id == userId
                            }
                        )
                    }
                }, rerunOnOpen: false)

//                Text("HELLO \(app.currentUser?.id ?? "")")

                OpenRealmView(
                    user: user,
                    onboardData: onboardData
                )
                .environment(\.realmConfiguration, config)
```

```
    @AutoOpen(
        appId: AtlasClient.shared.appId,
        timeout: 5000) var autoOpen

    @State var user: RealmSwift.User
    let onboardData: OnboardData?

    @Environment(\.realmConfiguration) private var config

    var body: some View {
        switch autoOpen {
        case .connecting:
            LoadingScreen()
        case .waitingForUser:
            LoadingScreen()
        case .open(let realm):
            RootContainer(shopper: {
                if realm.objects(Shopper.self).count == 0 {
                    try! realm.write {
                        let newShopper = Shopper()
                        realm.add(newShopper)
                    }
                }
                return realm.objects(Shopper.self).first!
            }()).environment(\.realm, realm)

        case .progress(let progress):
            LoadingScreen()
        case .error(let error):
            ErrorScreenView()
                .onAppear {
                    ErrorLoggingService.shared.recordError(error)
                    print("Error", error)
                }
        }
    }
    ```

But when I go offline I get the error "Failed to connect to sync. Host not found (authoritative)"

### Can you reproduce the bug?

Always

### Reproduction Steps

Behaviour:
When the device is online the realm opens.
When the device is offline, 
When the device is offline, I get the error "Failed to connect to sync. Host not found (authoritative)"

### Version

10.44.0

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

ios latest version

### Build environment

Xcode version: 15.0.1
Dependency manager and version: ...

**Comment by dvhull** [comment] 2024-01-23 22:03
For some reason this works on previous package versions but not the latest.

**Comment by dvhull** [comment] 2024-01-29 20:27
Where you ever able to find a fix to this @Jonovono ?

**Comment by nirinchev** [comment] 2024-02-06 12:04
This appears to be a duplicate of https://github.com/realm/realm-swift/issues/8469. I'll close this one and we'll continue the investigation in the other issue.

**Closed by nirinchev** 2024-02-06 12:04 UTC
Labels: T-Bug, O-Community, Frequency:Always, Repro:Always, Encryption:Off, SDK-Use:Sync
