### ISSUE TITLE
Issue with filter

### ISSUE THREAD

**Issue by negarhaghbin** [realm/realm-swift#7885] opened 2022-07-14 19:31 UTC
### How frequently does the bug occur?

All the time

### Description

I have this simple function that suppose to return `OfflineResource` objects that pass the predicate
```
fileprivate func searchOfflineResources(searchTerm:String) -> Results<OfflineResource>? {
        let predicate = NSPredicate(format: "name CONTAINS[cd] %@", searchTerm)
        return try? Realm().objects(OfflineResource.self).filter(predicate).sorted(byKeyPath: "name")
    }
```
My OfflineResource table contains an object named: **An"d**
When I use **n"** as `searchTerm` the function returns empty results but it works fine for any combinations not including a double quote.
The issue seems to happen for single quote character as well.

### Can you reproduce the bug?

Yes, always

### Version

10.28.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPhone 13 mini simulator (iOS 15.5) on a M1 Macbook pro

### Build environment

Xcode version: 13.4.1

**Comment by pavel-ship-it** [comment] 2022-07-15 09:40
Hi @negarhaghbin could you please confirm which quote symbol does not works for you?
```
        let quotes = ["“",
                      "”",
                      "‟",
                      "\"",
                      "″",
                      "˝",
                      "❝",
                      "❞",
        ]
```
Can you share a reproduction case or sample data?

**Comment by negarhaghbin** [comment] 2022-07-15 12:23
I'm seeing the issue with Quotation mark/Double quote with dec ascii code 34.

In my current app I have a textfield where I can write search terms.
```
public var searchInputText:String {
        get {
            return searchInputField.text ?? ""
        }
    }
```
I call `searchOfflineResources(searchTerm: searchInputText)` on the mentioned textfield change
`searchInputField.addTarget(self, action: #selector(searchOfflineResources), for: .editingChanged)`

This is how `OfflineResource` table look.

<img width="1304" alt="Screen Shot 2022-07-15 at 8 18 09 AM" src="https://user-images.githubusercontent.com/17231568/179221503-32e0a102-3aab-4239-bde5-c58b17d3cd7b.png">

Let me know if it helps with the reproduction.

**Comment by pavel-ship-it** [comment] 2022-07-15 15:30
@negarhaghbin Thank you for the details. I can reproduce the issue

**Comment by pavel-ship-it** [comment] 2022-07-15 16:08
@negarhaghbin that looks a bit interesting.
Could you tell me how do you input the quote char?
As you can see on the screenshot, the quote in the values - is 34
while the quote on the simulator keyboard is 8221
If I copy-paste the 34 symbol in the search field it find the required objects.
Can you confirm is it the issue or now?

![Simulator Screen Shot - iPhone 13 Pro - 2022-07-15 at 17 04 12](https://user-images.githubusercontent.com/66941868/179262869-53d87db8-724b-443c-9dbe-3a383f3ba5dc.png)

**Comment by negarhaghbin** [comment] 2022-07-15 16:14
I'm testing with an iPhone 13 mini simulator (iOS 15.5) on a M1 Macbook pro. I use my laptop's keyboard to input values.

**Comment by pavel-ship-it** [comment] 2022-07-15 16:20
Yep, that's same for me - I press Mac keyboard's quote - it types 8221 quote in the simulator's text field.
Same key will type 34 quote in XCode file

**Comment by dianaafanador3** [comment] 2022-09-12 11:41
@negarhaghbin It doesn't seem to be an issue in our side, this is happening because the stored value that is using (") with decimal code 34 and the string returned from the mac's keyboard used to filter is using code 8221. I'll close this as there is nothing to fix in our side.

**Closed** 2022-09-12 11:41 UTC
Labels: T-Bug, O-Community
