### ISSUE TITLE
Custom block filter like SectionedResults

### ISSUE THREAD

**Issue by andrefmsilva** [realm/realm-swift#8234] opened 2023-05-16 10:12 UTC
### Problem

I want to know if it's possible to filter Results with some custom closure (without using the Query API) with the trade off of recalculation every time the collection changes.

I have some filter logic that i can't translate to predicate because i need to do some data transformation before comparing values. Without a method to recreate Results with a small subset i have to load the items to memory and store them in array

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by ericjordanmossman** [comment] 2023-05-16 15:45
Custom block predicates aren't currently possible. This is something we've thought about for years but haven't pursued. I'll close this ticket as a duplicate of #2138 . Please feel free to comment there also.

**Closed by ericjordanmossman** 2023-05-16 15:45 UTC
Labels: T-Enhancement, O-Community, Importance:Major, SDK-Use:Local

**Comment by andrefmsilva** [comment] 2023-05-16 15:50
so basically i have to perform the first query -> filter -> perform another query with some unique filter
