### ISSUE TITLE
scattered reloc r_address too large for architecture i386

### ISSUE THREAD

**Issue by AlexIzh** [realm/realm-swift#7904] opened 2022-08-08 09:00 UTC
### How frequently does the bug occur?

All the time

### Description

After major update from 10.7.7 to the latest version we faced some weird issue when trying to compile the app with Apple Watch extension. 

Realm is used through SPM.
AppleWatch extension uses Realm as well.
Compiling for devices works fine, only simulator is a problem.

<img width="430" alt="Screenshot 2022-08-08 at 12 53 57" src="https://user-images.githubusercontent.com/2103547/183379562-fe370417-4cba-42e2-b330-2e5a30a2f020.png">

### Stacktrace & log output

```shell
Ld /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Intermediates.noindex/RealmDatabase.build/Debug-watchsimulator/RealmCore.build/Objects-normal/i386/Binary/RealmCore.o normal i386 (in target 'RealmCore' from project 'RealmDatabase')
    cd /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/SourcePackages/checkouts/realm-core
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target i386-apple-watchos2.0-simulator -r -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator8.5.sdk -L/Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Products/Debug-watchsimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/usr/lib -F/Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Products/Debug-watchsimulator/PackageFrameworks -F/Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Products/Debug-watchsimulator -iframework /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator8.5.sdk/Developer/Library/Frameworks -filelist /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Intermediates.noindex/RealmDatabase.build/Debug-watchsimulator/RealmCore.build/Objects-normal/i386/RealmCore.LinkFileList -nostdlib -Xlinker -object_path_lto -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Intermediates.noindex/RealmDatabase.build/Debug-watchsimulator/RealmCore.build/Objects-normal/i386/RealmCore_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -debug_variant -fobjc-arc -fobjc-link-runtime -Xlinker -dependency_info -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Intermediates.noindex/RealmDatabase.build/Debug-watchsimulator/RealmCore.build/Objects-normal/i386/RealmCore_dependency_info.dat -o /Users/alex/Library/Developer/Xcode/DerivedData/Project-evohrlyjldalplfwzjtxawskwehz/Build/Intermediates.noindex/RealmDatabase.build/Debug-watchsimulator/RealmCore.build/Objects-normal/i386/Binary/RealmCore.o

ld: scattered reloc r_address too large for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Can you reproduce the bug?

Yes, always

### Version

10.28.4

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Any iOS simulator

### Build environment

Xcode version: 13.4.1
Dependency manager and version: SPM

**Comment by leemaguire** [comment] 2022-08-08 10:40
Have you done a clean build / deleted derived data? Does this happen on a fresh project? I can't reproduce this, but I am also on a M1 Mac.

**Comment by AlexIzh** [comment] 2022-08-08 12:03
@leemaguire Yes, I have tried a clean build and deleting derived data. I'm trying on a fresh project right now but seems like I can't reproduce it either. It's weird that it worked with old Realm version though. I will spend more time on playing with a fresh project to see if it's something with configuration between my current and fresh projects.

**Comment by AlexIzh** [comment] 2022-08-08 17:26
Just to add some info: 
Tried to add all dependencies (SPM + Cocoapods) to the fresh project, also checked all configs -> still the fresh project doesn't have this issue. 
Tried to remove the whole codebase from problematic project except empty AppDelegate (and ExtensionDelegate), also removed all dependencies -> still RealmCore linking error.

Compared linking commands between the problematic project and the fresh one: 
```
-Xlinker -debug_variant
```
Only this parameter is different, everything else is exactly the same. According to [this page](https://keith.github.io/xcode-man-pages/ld.1.html#debug_variant) this parameter shouldn't make a lot of influence on a linking phase. But since these commands have a difference, it means something with configs, right? 

The question now: where it could be set/configured? It possible that some config influences on RealmCore compiling/linking only on latest versions for example.

**Comment by leemaguire** [comment] 2022-08-10 11:41
@AlexIzh would you be able to attach a sample project that replicates this issue? Also are you using an Intel Mac?

**Comment by leemaguire** [comment] 2022-09-01 14:06
Closing as issue cannot be reproduced and no more information given.

**Closed** 2022-09-01 14:07 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter
