### ISSUE TITLE
Configurable mongodb-realm root folder

### ISSUE THREAD

**Issue by jonathan-opuscope** [realm/realm-swift#7877] opened 2022-07-08 13:58 UTC
### Problem

We're running into some issues with a Hybrid Unity/Swift iOS app and Realm database approach. We have two realm applications running in the same iOS Application, one from the Unity .NET SDK the other from the Swift SDK. It works mostly but we're having some issues which are not easy to reproduce and seem to be linked to startup Timing. We have forced the Unity and Swift SDKs to use different realm storage files (configuration.DatabasePath and configuration.fileURL respectively) but some issues persist. Looking at the hierarchy of the mongodb-realm folder (which is used by both SDKs), it seems there are a number of auxiliary files whose path cannot be configured and it seems likely that the issues we are running into are due to concurrent access to auxiliary files. 

### Solution

We would need to be able to configure the root folder (mongodb-realm) to be fully separate for Unity and Swift (say mongodb-realm-unity and mongodb-realm-swift). 

### How important is this improvement for you?

Important as we will otherwise have to use only one of the SDKs and push/pull data to the Unity process

**Comment by dianaafanador3** [comment] 2022-07-08 17:17
Hi @jonathan-opuscope you can override the path of the synced realm file using fileUrl
```
var config = user.configuration(testName: "partition") or user.flexibleSyncConfiguration()
config.fileURL = customFileURL
let realm = try await Realm(configuration: configuration)
```
Remember to create the directory, if you are using a different directory and set the permission on it.

You also can do this as well on the `.NET` SDK setting the [BaseFilePath](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.AppConfiguration.html#Realms_Sync_AppConfiguration_BaseFilePath) property of AppConfiguration. 
You only need ro do this for one of the SDK and you will solve your issue.

**Comment by dianaafanador3** [comment] 2022-07-08 19:18
Hey again @jonathan-opuscope. I misinterpreted the questions, I was talking about the path of the realm file instead of the mongodb-realm folder which I think it is what you really want. You can still use the .NET solution mentioned in the above message. Changing it there and  let the Realm-Swift SDK use the default location will solve your issue.

**Comment by jonathan-opuscope** [comment] 2022-07-11 08:33
Thanks for the answer @dianaafanador3. Not sure I understand, the .NET `configuration.DatabasePath` refers to the `.realm` file (i.e. the equivalent of the swift `configuration.fileURL`), as far as I can see neither allows me to change the root folder and consequently the path of the auxiliary files.

**Comment by jonathan-opuscope** [comment] 2022-07-11 08:36
Thanks! I'll try the [BaseFilePath](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.AppConfiguration.html#Realms_Sync_AppConfiguration_BaseFilePath)

**Comment by jonathan-opuscope** [comment] 2022-07-11 08:36
Thanks! I'll try the [BaseFilePath](https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.Sync.AppConfiguration.html#Realms_Sync_AppConfiguration_BaseFilePath)

**Comment by dianaafanador3** [comment] 2022-07-11 10:14
Hi @jonathan-opuscope let us know if the issue is fixed so we can close the issue, or if you need any help.

**Comment by jonathan-opuscope** [comment] 2022-07-12 16:30
Sorry for the delay, did the job ! Thanks a lot. Probably worth adding to the swift SDK though :)

**Comment by pavel-ship-it** [comment] 2022-07-18 10:45
@jonathan-opuscope Thank you for the update. I close the ticket then

**Closed by pavel-ship-it** 2022-07-18 10:45 UTC
Labels: T-Enhancement, O-Community, Needs-Attention
