### ISSUE TITLE
Realm Migration strange behaviour in case of not increasing the Schema Version

### ISSUE THREAD

**Issue by rajatgupta9021** [realm/realm-swift#7787] opened 2022-05-08 15:38 UTC
### How frequently does the bug occur?

All the time

### Description

Hi Team, 

We are facing one strange behavior while trying to upgrade the application. We have added the two properties in the Realm table and didn't increase the schema version. So while upgrading with the current Testflight App, we are not getting the exception while trying to do the realm migration. 

Expected Behaviour: It should throw the exception if we have made some modifications in the Realm table and didn't increase the schema version. 

We are able to replicate this behavior in debug builds through Xcode(While deleting the derived data) and Appstore builds. 

Can you please guide why we are getting this inconsistent behavior?

### Can you reproduce the bug?

Yes, always

### Version

10.22.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 13 and iOS 14

### Build environment

Xcode version: 13.1
Dependency manager and version: ...

 - Realm (10.22.0):
    - Realm/Headers (= 10.22.0)
  - Realm/Headers (10.22.0)
  - RealmSwift (10.22.0):
    - Realm (= 10.22.0)

**Comment by leemaguire** [comment] 2022-05-10 13:53
Hi @rajatgupta9021 I cannot reproduce the issue. Could you send us a sample project that replicates this behaviour?

**Comment by leemaguire** [comment] 2022-08-26 10:52
Closing this issue as no reproduction case has been provided from the user.

**Closed** 2022-08-26 10:56 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter
