### ISSUE TITLE
@AutoOpen doesn't work

### ISSUE THREAD

**Issue by egg1102** [realm/realm-swift#8489] opened 2024-02-16 18:10 UTC
### How frequently does the bug occur?

Always

### Description

AutoOpen should work offline first however it doesn't. 

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Go into a realm project with @AutoOpen on a actual device. 
2. Authenticate the user with a internet connection. 
3. Turn on airplane mode or get rid of internet connection wait 2 minutes. 
4. Get a sync connection errors. 

### Version

10.45.3

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Xcode version: 15.0
Realm: 10.45.3

**Comment by nirinchev** [comment] 2024-02-17 00:36
This is a duplicate of https://github.com/realm/realm-swift/issues/8469.

**Closed by nirinchev** 2024-02-17 00:36 UTC
Labels: T-Bug, O-Community, Frequency:Always, Repro:Always, Encryption:Off, SDK-Use:Sync
