### ISSUE TITLE
Unable to compile Realm when targetting watchOS

### ISSUE THREAD

**Issue by mwoollard** [realm/realm-swift#7623] opened 2022-01-20 15:14 UTC
### How frequently does the bug occur?

All the time

### Description

Am using Realm integrated in a pure SPM library project that targets iOS, tvOS macOS and watchOS. With latest update of packages can no longer build for watchOS. The error is:

```
.../simulated_failure.cpp:174:1: error: thread-local storage is not supported for the current target
thread_local bool (*s_mmap_predicate)(size_t);
^
1 error generated.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Sample project is available [here](https://github.com/mwoollard/realm-watchos)

clone project
from project root directory

$ open Package.swift

In xcode select watchOS as run target

Build

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

watchOS 7.4. up

### Build environment

Xcode version: 13.2.1
Dependency manager and version: Xcode SPM (swift 5.5.2)

**Comment by leemaguire** [comment] 2022-01-21 10:17
Hi @mwoollard. I still cannot reproduce your issue even with the sample project. Are you using macOS Monterey?

**Comment by mwoollard** [comment] 2022-01-21 10:23
Yes, using Monterey, am also seeing this both on my dev laptop (M1) within Xcode and CI scripted builds (Intel).

**Comment by mwoollard** [comment] 2022-01-21 11:30
Additional, FWIW, if I change the compile time condition @ line 171 to
```
#if (REALM_ARCHITECTURE_X86_32 && REALM_IOS) || REALM_WATCHOS
```
Code compiles

**Comment by dianaafanador3** [comment] 2022-01-24 18:05
Thanks for the suggestion, I created a PR for it on core. You can keep track of the issue here and on the PR https://github.com/realm/realm-core/pull/5188.

**Comment by dianaafanador3** [comment] 2022-02-08 11:47
This has been fixed on core and will be available shortly.

**Closed by dianaafanador3** 2022-02-08 11:47 UTC
Labels: T-Bug, O-Community

**Comment by stremblayiOS** [comment] 2022-03-08 16:38
This is still happening using SPM and `Realm 10.24.0`. Can we reopen this please?

**Comment by dianaafanador3** [comment] 2022-03-08 16:40
Are you still getting the same error?

**Comment by stremblayiOS** [comment] 2022-03-08 16:41
yes

**Comment by mwoollard** [comment] 2022-03-08 16:43
I think this is now only issue when targeting M1 simulator. I created new issue in realm-core [here](https://github.com/realm/realm-core/issues/5310). Could you confirm you are using M1 Mac?

**Comment by stremblayiOS** [comment] 2022-03-08 16:59
I am not using a M1 Mac.

**Comment by stremblayiOS** [comment] 2022-03-08 17:44
This is what I get when I try to add Realm to an watch extension using SPM

<img width="364" alt="Screen Shot 2022-03-08 at 12 44 04 PM" src="https://user-images.githubusercontent.com/919665/157295213-b771caad-c252-4b7b-a4ae-020472c76978.png">

**Comment by ding-stephen** [comment] 2022-03-27 13:11
The same issue for my project with the latest Realm 10.24.2 on my Intel Mac.
But the problem is only happened on the simulators, not when testing on actual device.

![截屏2022-03-27 21 08 31](https://user-images.githubusercontent.com/12482183/160282965-b993a054-e8e3-4447-8306-97c4e89389db.png)

**Comment by philipengberg** [comment] 2022-04-16 17:43
@dianaafanador3 Facing the same issue, I can confirm that your branch fixed the issue for me (on WatchOS). Any plans to merge these changes?
